### ISSUE TITLE
Lecturer is able to log in/Register 

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#1]
- signing up using the special endpoint will give the lecturer the administrator functionality.
- Fullname
- use university emails only

- Sign out.

**Comment by minaorangina** [comment]
**Estimated time: 1 day**

**Comment by stianr** [comment]
May be best to leave out only allowing university email addresses, if it was going to be constrained to '.ac.uk' or similar. Otherwise I won't be able to demonstrate to colleagues in other countries.

**Comment by minaorangina** [comment]
@stianr Ok, we will accept all valid email addresses.
