### ISSUE TITLE
Edit Score: view student result for each question in the given quiz.

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#107]
#10

When the lecturer enters the edit-score section. They should also see all the responses given by all the users who have partaken in the given quiz. 

![screen shot 2016-08-18 at 11 25 47](https://cloud.githubusercontent.com/assets/2305591/17770615/89ce03d0-6536-11e6-9fe7-28e33be2ba08.png)

**Comment by minaorangina** [comment]
#### fetch all students' responses
- [ ] onEnter `/:module/:quiz/members`

**Comment by sohilpandya** [comment]
Look into **tablefunc** and **crosstab**

**Comment by minaorangina** [comment]
Was decided that this level of detail about students' performance was unnecessary.
