### ISSUE TITLE
As a lecturer I can manage all the students in a module

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#11]
- viewing performance history in detail
- deleting student
- adjusting student scores for individual quizzes

**Comment by minaorangina** [comment]
@stianr In the event a lecturer adjusts a student's score, should this be reflected in medals/trophies awarded?

For instance, if a student goes from 9/10 to 10/10, does the student then receive the full marks trophy after that?

Similarly, if a student goes from 6/10 to 7/10, should the medal awarded reflect this change?

**Comment by stianr** [comment]
Yes, I think it should update the trophies/medals so when they login or see the leaderboard it’s there, but it shouldn’t generate an alert to the student when they log in or complete another quiz.
