### ISSUE TITLE
Edit Quiz: Saving to an existing quiz

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#113]
@minaorangina 
#8 

I am trying to think of the best way to create a query which will save to an existing quiz, just wanted to write it down here and maybe can figure out the best way to deal with this query. 

When user edits the quiz, they may add additional questions or just edit existing questions. 

How does the query tackle this? This is what my current thinking is.

- For loop on each question.
- For each question check if it has question id and whether it exists.
- If it exists then update 
- else add new question. 

Repeat for all the questions in the questions array. 

How does that sound?

**Comment by minaorangina** [comment]
@sohilpandya You're thinking in JavaScript, when you should be thinking in SQL.  The idea of have a querying language is that it does the sort of heavy lifting that we would ordinarily have to do for ourselves with something like Redis.  

You don't have to worry about looping or any other implementation details.  To solve this problem, all you need is to compose the right sort of query, and the database will handle it.

So first of all, you need to think about what you're asking the database to do for you.  Once you've decided what you want from it, the next step is to actually find out what the SQL syntax would be.
