### ISSUE TITLE
Keyboard events to submit/proceed

### ISSUE THREAD

**Issue by minaorangina** [cul-2016/quiz#114]
Places like the login page etc don't currently listen to keyboard events.

Should be able to hit Enter on the keyboard and achieve the same affect as clicking a button

**Comment by sohilpandya** [comment]
In React we have used onKeyDown instead of onKeyPress as the keyCode is only present on key down. it does not exist for key press. 
```
onKeyDown={ (e) =>  if (e.keyCode === 13) return something }
```
