### ISSUE TITLE
Create `get-feedback` endpoint and associated actions

### ISSUE THREAD

**Issue by minaorangina** [cul-2016/quiz#150]
#121 
* `get-feedback` request
* `GET_FEEDBACK` async actions
* `get-feedback` route and handler function

**Comment by sohilpandya** [comment]
Hi @minaorangina, where should the actions/reducers go for this? should I be creating a new feedback state? or you'd like me to add this to an existing area?

**Comment by minaorangina** [comment]
@sohilpandya Create a new one I reckon. I can't think of any pre-existing areas that seem sensible
