### ISSUE TITLE
Feedback: server function to get participation rate

### ISSUE THREAD

**Issue by minaorangina** [cul-2016/quiz#154]
#121 
* query to calculate how many quizzes student has participated in
* separate query to get total number of quizzes in the module. 

Values from this should be bundled in an object.  Eventually they would be combined with the percentile and strengths/weaknesses values in the `/get-feedback` endpoint handler

Currently, minimum quizzes required for this feedback to be relevant is 4.  This will be handled on the client side.

**Comment by sohilpandya** [comment]
Here is the query for the participation rate: 

```
select COUNT(DISTINCT(quizzes.quiz_id)) as participation, (SELECT count(quiz_id) as TotalNumQuizzes FROM quizzes WHERE module_id = 'TEST'), ( SELECT CAST (COUNT(DISTINCT(quizzes.quiz_id)) AS FLOAT) /
( SELECT CAST (count(quiz_id) AS FLOAT) FROM quizzes WHERE module_id = 'TEST') * 100 as average ) from quizzes inner join responses on quizzes.quiz_id = responses.quiz_id where quizzes.module_id = 'TEST' and responses.user_id = 1 group by responses.user_id;
```

And here is the result it returns:
#### `Participation Rate` table
| participation | totalnumquizzes | average |
|---|---|---|
|4| 5 | 80 |

@minaorangina So this whole query returns the total number of quizzes a user has participated in for a given module, total number of quizzes for a given module alongside the average participation rate for the given user (basicall paricipation / totalnumquizzes * 100)

Are you ok with this query?

**Comment by minaorangina** [comment]
@sohilpandya looks good to me.  Just tidy up the query itself a bit (e.g. capitalising in the right places, snake case instead of camel case) and write some tests to make sure it definitely works the way you're expecting
