### ISSUE TITLE
Create `Participation` component

### ISSUE THREAD

**Issue by minaorangina** [cul-2016/quiz#155]
#121 

### If total number of quizzes is fewer than 4
_no mention of a specific message_

### If submission rate >= 75% (e.g. user has submitted 3 of 4 quizzes)
* It’s great that you’re taking part in most of the quizzes. Each time you try to recall information, as you do when you complete a quiz, you make it easier to remember that information later. So you’re helping your learning with each quiz you take.

### If submission rate < 50% (e.g. user has submitted 2 of 5 quizzes)
* You’re not taking part in a lot of the quizzes. If you’re playing along in your head but not submitting the answers then that’s great, but if you’re missing some of the quizzes, then you’re putting yourself at a disadvantage. Remember, each time you try to recall information, as you do when you complete a quiz, you make it easier to remember that information later. So you’re helping your learning with each quiz you take.

**Comment by minaorangina** [comment]
@stianr Did you want any particular message to be displayed in any cases other than the ones outlined above?  For instance, a message when a student has submitted fewer than 4 quizzes, or when the submission rate is between 50% and 74%?

**Comment by stianr** [comment]
### If submission rate >= 50%  and <75%

- You're completing over half of the quizzes, which is great, but you're also missing some. The more quizzes you complete, the easier you'll find it remember that information later. So you’re helping your learning with each quiz you take.

### If <4 quizzes have been run

- We haven't run enough quizzes to give you detailed feedback on your participation yet.

Note that the feedback based on submission rate should only be shown if >=4 quizzes have been run.
