### ISSUE TITLE
Add detailed information about quiz performance

### ISSUE THREAD

**Issue by minaorangina** [cul-2016/quiz#165]
#11 
Should be able to see for each quiz
* a 'table' of questions
* number of students that got it right
* number of student that got it wrong
* some reference to the name of the quiz and the answers to each question

The idea is to have a reference to the quiz stats that a lecturer can refer to after a quiz has taken place

Lecturer should be able to see which questions students did well on at a glance

Emphasis is on the general stats, rather than on individual scores per student

**Comment by sohilpandya** [comment]
@minaorangina going for dinner now, will pick it up later in the evening. here is how it looks at the moment, what do you think? (apart from it being a bit too big)

![screen shot 2016-09-13 at 18 11 08](https://cloud.githubusercontent.com/assets/2305591/18483788/9a1113b6-79dd-11e6-9a1f-ed780c56ef52.png)

**Comment by minaorangina** [comment]
@sohilpandya it doesn't scale well.  it will take only 3 or 4 questions for the whole view to be full.  it needs to be much more compact

**Comment by sohilpandya** [comment]
Yeah, I agree, trying to figure out what the best approach for styling it will be, but in terms of the information, this all looks good right?

**Comment by sohilpandya** [comment]
@minaorangina check this out -
![screen shot 2016-09-14 at 16 04 55](https://cloud.githubusercontent.com/assets/2305591/18517689/0e16df4a-7a95-11e6-95bc-1fddc6be946e.png)

How does it look?

**Comment by minaorangina** [comment]
@sohilpandya looking better.   The edit score buttons need to move over away from the scores a bit though.  Also can you change username to nickname in the component please?

I have an idea for the edit score button.  I reckon it should appear on hover of the row in question, to make it look less cluttered.  So you'd only see one edit score button at a time, when your cursor is over it.   What do you think?

**Comment by minaorangina** [comment]
Oh also @sohilpandya, there ought to be some sort of order to the list.  Alphabetically by email most likely

**Comment by sohilpandya** [comment]
@minaorangina atm it's ordered by score. should we change it to sort by nickname rather than email? just seems more sensible. what do you think?

**Comment by minaorangina** [comment]
@sohilpandya I feel email address might be more sensible, because the nickname could literally be SpaghettiHoops4000, which would mean nothing.  Whereas the email address is likely to be something like *firstname.surname@university.ac.uk*.  But pick whichever, it can be easily changed anyway.

Also I've noticed that "score" needs to be capitalised at the top of the table

**Comment by sohilpandya** [comment]
OK, I've sorted it by email for now.
