### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#173]
@minaorangina 

How does this look 

### New Module
![screen shot 2016-09-15 at 14 58 51 2](https://cloud.githubusercontent.com/assets/2305591/18552604/001c1c0a-7b55-11e6-98ff-c1a12c209b4e.png)

**Comment by sohilpandya** [comment]
### Dashboard

![screen shot 2016-09-15 at 16 42 19 2](https://cloud.githubusercontent.com/assets/2305591/18556511/6b331e0e-7b63-11e6-9848-18dd7296ee61.png)

**Comment by sohilpandya** [comment]
### Module Details

![screen shot 2016-09-15 at 18 12 40](https://cloud.githubusercontent.com/assets/2305591/18559628/09cc097a-7b70-11e6-916d-b479364a806b.png)

**Comment by minaorangina** [comment]
### Dashboard: student view

After merging your PR I've looked at the student dashboard - I don't remember if you said it was a WIP, but it needs to be changed.  Doesn't work at all unfortunately.

![screen shot 2016-09-16 at 16 48 12](https://cloud.githubusercontent.com/assets/8915092/18592185/a4342cc8-7c2d-11e6-8153-d3158b112ec4.png)

**Comment by sohilpandya** [comment]
I'll change it to the way it was.
