### ISSUE TITLE
Learn postgres

### ISSUE THREAD

**Issue by minaorangina** [cul-2016/quiz#19]
## Resources
- [pgexercises](https://pgexercises.com/questions/basic/selectall.html)
- [CS50 explanation](http://cs50.tv/2012/fall/shorts/sql/sql-720p.mp4)
- [Udacity Intro to Relational Databases](https://www.udacity.com/course/intro-to-relational-databases--ud197)
- [Codecademy Learn SQL](https://www.codecademy.com/learn/learn-sql)
  - [List of SQL commands (codecademy)](https://www.codecademy.com/articles/sql-commands?r=master)
- [pgadmin](https://www.pgadmin.org/)
- [Tutorials Point](http://www.tutorialspoint.com/postgresql/postgresql_create_table.htm)
- [Blog: realtime web apps w/ postgres and node](http://darrenoneill.co.uk/post/real-time-web-apps-postgresql-and-node/)
- [sqlzoo](http://sqlzoo.net/)

**Comment by minaorangina** [comment]
[CS50 explanation](http://cs50.tv/2012/fall/shorts/sql/sql-720p.mp4)

**Comment by minaorangina** [comment]
[Udacity Intro to Relational Databases](https://www.udacity.com/course/intro-to-relational-databases--ud197)

**Comment by minaorangina** [comment]
[Codecademy Learn SQL](https://www.codecademy.com/learn/learn-sql)

**Comment by minaorangina** [comment]
##### [List of SQL commands (codecademy)](https://www.codecademy.com/articles/sql-commands?r=master)

**Comment by sohilpandya** [comment]
SQL `IN` command returns items in table that match any of the arguments.

`select * from cd.facilities where facid in (1,5)`

**Comment by sohilpandya** [comment]
pgadmin

**Comment by sohilpandya** [comment]
http://www.tutorialspoint.com/postgresql/postgresql_create_table.htm

**Comment by sohilpandya** [comment]
http://darrenoneill.co.uk/post/real-time-web-apps-postgresql-and-node/

**Comment by minaorangina** [comment]
### Joins
Use joins to get data from multiple tables.

Inner join
Combines rows from different tables if the join condition is true.

#### Example

```bash
SELECT * FROM modules 
JOIN medals 
ON modules.module_id = medals.module_id
```

**Comment by minaorangina** [comment]
[sqlzoo](http://sqlzoo.net/)

**Comment by sohilpandya** [comment]
### Case

Case is a conditional (i.e. an if statement).

#### Example  
Simplest example to use with our database is to list number of responses for a given question.
```
select 
count(case when response = 'A' then 1 end) as a_response, 
count(case when response = 'B' then 1 end) as b_response, 
count(case when response = 'C' then 1 end) as c_response, 
count(case when response = 'D' then 1 end) as d_response  
from responses 
where quiz_id=1 and question_id=1
```
This returns a new table with 4 columns and 1 row containing the accumulation of responses.

**Comment by minaorangina** [comment]
### "Upserting"

This references when you want to either insert a value or, if it exists already, update it.

Postgres 9.5 makes this possible with the `ON CONFLICT DO UPDATE` clause.
Used this to solve issue #76, specific implementation may be found [here](https://github.com/cul-2016/quiz/issues/76#issuecomment-240793696)

**Comment by minaorangina** [comment]
### Composite primary key

Usually you'll uniquely identify a row by a primary key - perhaps a self-incrementing id.  But you might have a table where there's no column with completely unique values.  Instead, a particular combination of values are what make a row unique.

You can actually combine multiple keys into one primary key, or make a particular combination of keys unique.

```
CREATE TABLE IF NOT EXISTS module_members (
    module_id CHAR(4) NOT NULL,
    user_id INTEGER NOT NULL.
    PRIMARY KEY (module_id, user_id)
);
```

Alternative could be:
```
CREATE TABLE IF NOT EXISTS module_members (
    module_id CHAR(4) NOT NULL,
    user_id INTEGER NOT NULL.
    UNIQUE (module_id, user_id)
);
```

**Comment by minaorangina** [comment]
### Distinct
Let's say we want a list of students who have taken part in a quiz
```
SELECT DISTINCT(user_id) FROM responses WHERE quiz_id = $1;
```

**Comment by minaorangina** [comment]
### Count
If you need to count rows, you can do it like this:
```
SELECT COUNT(user_id) FROM module_members WHERE module_id = $1;
```

**Comment by minaorangina** [comment]
Lifted from #47, [here](https://github.com/cul-2016/quiz/issues/47#issuecomment-234288684)

### For each of this category, do some maths
```
SELECT arbitrary_category, SUM(my_column) FROM table GROUP BY arbitrary_category
```
```
SELECT arbitrary_category, COUNT(my_column) FROM table GROUP BY arbitrary_category
```
`COUNT/SUM ... ...  GROUP BY`
This says: _group things up in this arbitrary category, then reduce the members of that category down to one value_


### For each of this category, do some maths, then do some more maths
```
SELECT arbitrary_category, COUNT(my_column) FROM table GROUP BY arbitrary_category
```

**Comment by minaorangina** [comment]
### Comparison operators

#### Not equal to
`<>` or `<!=>`

```bash
SELECT medal_name, condition FROM medals WHERE module_id = 'TEST' AND medal_name <> 'gold';
```

**Comment by sohilpandya** [comment]
### Delete Multiple rows from a table

```
 DELETE FROM table WHERE id IN (?,?,?,?,?,?,?,?)
```

**Comment by sohilpandya** [comment]
### Converting integers to floats.

when you calculate 3/4 it should return 0.75, but because sql is strongly typed, it needs to know that you are after floats. 

Hence use 
```sql
CAST (3 AS FLOAT) / CAST (4 AS FLOAT)
```
 to get the return value of 0.75

**Comment by iteles** [comment]
@minaorangina @sohilpandya We can probably close this one now? ;)

**Comment by minaorangina** [comment]
This issue was moved to DRDD2016/api#40
