### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#196]
There are compatibility issues with different browsers. These include:
- I can't login/register under IE11 (Click login, and it shows the loading circle but does not progress)
- Login box is not centered under IE11
- Text for buttons either appears outside buttons or does not appear at all under Firefox. E.g., "To Dashboard", "Manage Students"

Will add any others to this thread.

![firefox_buttons](https://cloud.githubusercontent.com/assets/16817089/19109446/5c3cdd2e-8aed-11e6-8211-fd9bcc6d571e.JPG)

**Comment by stianr** [comment]
- Under Firefox for Android, entering four letter code to join a module is buggy. If I type 'abcd', it gives 'AABABCABCD'. Doesn't happen for digits or capital letters, so assuming it's something to do with the process of captalisation.

**Comment by minaorangina** [comment]
@stianr Which browsers are the main ones that will be used on the university computers?  You've mentioned IE11 already, is that the principal browser of choice for most lecturers?

**Comment by stianr** [comment]
Our learning technologists recommend Firefox, but most people tend to use either Internet Explorer or Chrome. So we probably need to check all. Not sure about which version of IE - it was 11 on my office machine, but I'll check what they have in the lecture theatres and get back to you.

________________________________

**Comment by stianr** [comment]
![ie11](https://cloud.githubusercontent.com/assets/16817089/19263690/6aa5e64c-8f95-11e6-8b78-2f12a968f422.JPG)

This is what it looks like on IE - it just stops at this point and never logs in. Seems to work fine on Edge though.

**Comment by sohilpandya** [comment]
@stianr what version of Firefox are you running on your Android phone? could you please delete and reinstall Firefox and see if the issue is still present. 

We've installed firefox for Android on a Samsung Galaxy S6 and the repetition isn't taking place on our device. 

Just wanted to eliminate a few things before trying to re-write some of the code.

**Comment by stianr** [comment]
It’s version 49.0 run on a Galaxy S5 - which seems to be the latest one. I’ve uninstalled and reinstalled and get the same thing again. It's only on the page where you enter the 4-letter module code.

**Comment by stianr** [comment]
Registration and login don't work on iPhone 4S Safari under iOS 7.1.2. Login/registration page displays, but nothing happens after submit button pressed. Like with IE11. Can you confirm which version of iPhone/iOS it is currently compatible with?

**Comment by stianr** [comment]
Currently only the issue in my second comment above is still open: 

Under Firefox for Android, entering four letter code to join a module is buggy. If I type 'abcd', it gives 'AABABCABCD'. Doesn't happen for digits or capital letters, so assuming it's something to do with the process of captalisation.

**Comment by stianr** [comment]
Great - works on Firefox, and still manages to convert to uppercase.
