### ISSUE TITLE
Student experience of completing quiz

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#197]
- After submitting answer on the first question, the submit button changes to ‘resubmit answer’, and stays like that for the rest of the quiz. It needs to change back to ‘submit’ when the next question appears.
- Medal needs to be shown where user sees their score for the first time at the end of the quiz. Best if the score appears inside the medal.
- At the end of the quiz ‘Finish’ doesn’t do anything, so the user is stuck on the final page. Needs to return user to summary page for that module

**Comment by minaorangina** [comment]
@stianr Thanks for these.  The 'Finish' button not doing anything is actually a bug - will fix.
