### ISSUE TITLE
Student registration / login

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#204]
We have no way of retrieving or resetting a user's password once they've registered, which I can see leading to issues where people have a typo in their password when registering or forget it after registering. To mitigate this, could we do the following:
- Make the password visible so users can see more easily if they've made a typo
- Have the login last as long as possible - if it's possible to keep students logged in indefinitely that would be ideal.

**Comment by sohilpandya** [comment]
HI @stianr, 

- We feel it may be better to have a confirm password field which would only let you register when they match.

What do you think about this suggestion?

**Comment by stianr** [comment]
Yes, that sounds sensible.

S.

**Comment by minaorangina** [comment]
Solved.  Reason was that IE11 did not have a Promise API, which was needed for axios.
Followed suggestions made [here](https://github.com/mzabriskie/axios/issues/135)

**Comment by stianr** [comment]
I don't think the extending login duration has been implemented yet. If it's just a case of changing a cookie expiration time or similar, it'd be great to keep people logged in, as I've already had a few people register twice because they forgot their login details. If it's much more work than that, then please comment - we can roll it over to the next sprint and I'll close this.
