### ISSUE TITLE
Leaderboard displays NaN for uncompleted quizzes

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#217]
![leadeboard](https://cloud.githubusercontent.com/assets/16817089/19394304/77118baa-9230-11e6-97d8-ef2b1861def2.JPG)

**Comment by stianr** [comment]
Also, can we change the "Average Score %" column heading to "Total Score".

**Comment by sohilpandya** [comment]
@stianr Could you please test and close the issue if it's ok.

We think this issue was fixed a while back.

**Comment by stianr** [comment]
Yes, haven't experienced that issue running recently.
