### ISSUE TITLE
Full screen / remove inactive scrollbar for quiz

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#218]
![scrollbar](https://cloud.githubusercontent.com/assets/16817089/19394799/873b2a20-9232-11e6-845d-51af0d769b36.JPG)

The scrollbar is still visible on the right of the screen, even when everything fits within the page. Can it be set to disappear when scrolling is not required?

Even better, can we have a 'go full screen' button at the start of the quiz, rather than having to hit F11 to do it manually. If that's difficult, don't worry about it.

**Comment by stianr** [comment]
We no longer need the labels A, B, C, D on either the quiz or the answers, given that people just press the button they think is right. Can we drop those, to tidy up the screen a bit so rather than having "A: Xxxxx", we just have "Xxxxx".

**Comment by minaorangina** [comment]
@stianr this is done now, with the exception of a button for fullscreen mode, which is a bit tricky to implement at this stage

**Comment by stianr** [comment]
Great. No problem re fullscreen.

**Comment by stianr** [comment]
Scroll bar:

Edge: No scrollbars present
Chrome: Active vertical and horizontal scrollbars present during quiz presentation - resizing doesn't help, as always seems to be slightly larger than space on screen... 
Firefox: Inactive vertical scrollbar still present
