### ISSUE TITLE
Illumination of Join Quiz button

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#226]
The greyed-out button that turns yellow for students when the quiz is activated, allowing students to join the quiz, does not illuminate for all users. This has happened both times the quiz has been run. A manual page refresh followed by a short wait makes it work on the users' devices.

**Comment by minaorangina** [comment]
@stianr So the way the button illumination works is that there's an initial signal sent out to all phones to illuminate the button, then that signal is repeated every 5 seconds (which would explain the short wait).  

There's no clear diagnosis as to why the button wouldn't illuminate at all for some students, could be attributed to a temporary dip in connectivity perhaps?

**Comment by stianr** [comment]
I've now seen this firsthand - I invited people to join the quiz. The four other participants saw the 'join quiz' light up, but for one it remained greyed out. I watched it for around 30 seconds, then did a manual page refresh (which happened instantaneously suggesting it wasn't a connection issue), after which, a couple of seconds later, the button illuminated. This was on an iPhone 4S, but in the lecture I think it happened with a more recent iPhone.

**Comment by minaorangina** [comment]
@stianr The fact this happens for one or two people, then starts working, is incredibly difficult to diagnose.  We'll have to see if we can reproduce the problem on our side

**Comment by stianr** [comment]
That makes sense. In this afternoon’s quiz, I’ll leave it a little longer in case that’s the cause.

**Comment by stianr** [comment]
Logging devices where issue is seen - for fixing in next sprint:
iPhone 4S (rectified by manual refresh)
iPad (rectified by manual refresh)

**Comment by iteles** [comment]
@franzmoro @sohilpandya Assigning to you for a time estimation (so that @stianr can prioritise this based on it) please!

**Comment by sohilpandya** [comment]
We have discussed this issue #226, We have also tried to replicate the issue in an iPhone 4s Simulator running iOS 8.1 (in Xcode), unfortunately, we were unable to replicate the issue. 

We are unable to run an older version of iOS in a simulator as the older version that Apple provides access to on a simulator is 8.1

**Comment by stianr** [comment]
I have seen this issue with multiple devices including more recent iPhones. Suspect it's down to connectivity, which a simulator might not catch?, rather than OS, but no way of knowing until we get more data on where and when it happens. Hard to estimate time, I'm sure, but we should leave some time for a couple of months' time, if possible, to debug after user testing. Enough people had a problem that we'll need to get to the bottom of it (if it doesn't disappear with the latest version).

One very specific thing that a user brought up in feedback was that when they locked and then unlocked their iPhone during the quiz, it no longer updated the questions. So that might be a first thing to check.

But let's leave this until we get more user feedback - we could end up chasing shadows.

**Comment by stianr** [comment]
I've tried to replicate the issue. I don't have an iPhone, so it might be different on different devices, but on a Galaxy 5 / Firefox I simulated a short interruption to connectivity by switching to flight mode for a few seconds and then back. If as a lecturer I invited students to join the quiz while flight mode was on for the student account, the 'Join Quiz' button never illuminated for the student once the connection was restored. (A manual refresh of the page brought it back.) Similarly, if as a lecturer I moved on to another question while the student phone was in flight mode, when the connection was established again, the student stayed stuck on the question they were on as the lecturer moved through later questions.

So might it be that if the user's quiz fails to make a connection with the server, it gives up and doesn't try again, or similar? Or something along those lines?

**Comment by stianr** [comment]
To add to this, the same issue arises on my android phone if I switch between 4G and wifi during the quiz (e.g., if wifi is off initially, and I switch it on, then the phone automatically switches over from 4G to wifi when it detects a familiar network).

**Comment by stianr** [comment]
Closing this as it has drifted a long way from the initial bug report. Have created a broader issue re getting stuck, in #338, of which issue initially reported here is an example.
