### ISSUE TITLE
Trophies disappearing from leaderboard

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#229]
It looks like if a student gets a trophy for getting 100% in a quiz, and then in the next quiz they get <100%, the trophy disappears. I've seen this on the leaderboard - not sure if it also occurs on the student's own page. Once a trophy has been awarded it should not be withdrawn from either.

**Comment by stianr** [comment]
It now seems to have gone the other way - after today's quiz, everyone who completed it got a trophy for 100%, whatever their score (check out the SPSY leaderboard). Is that fixable?

**Comment by minaorangina** [comment]
Problem is here:

https://github.com/cul-2016/quiz/blob/staging/server/lib/trophy-methods.js#L33-L36

* `high_score` is the wrong value - Currently it's the whole object returned from the database, as opposed to the Boolean value we're expecting.  Solution would be:
```js
var high_score = result.rows[0];
if (high_score) {
...
}
```
* Should be some error handling on line 34

**Comment by minaorangina** [comment]
@stianr this should be fixed now

**Comment by stianr** [comment]
Thanks.
