### ISSUE TITLE
Lecturer can access other lecturers' quizzes

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#230]
If a lecturer is logged in on their module XXXX, with URL

http://cul-app.herokuapp.com/#/XXXX/lecturer?_k=65wenr

they can gain access and edit rights to any module (e.g. YYYY) owned by any user just by replacing the XXXX with the code for the module 

http://cul-app.herokuapp.com/#/YYYY/lecturer?_k=65wenr

Any request to view or edit any post login page needs to check that the user making the request has permission.

**Comment by sohilpandya** [comment]
We've put the authorisation function `checkModuleOwner` in the onEnterHooks. This will redirect any unauthorised lecturers back to the dashboard.

Here are the routes where this authorisation does not take place.
```
:module_id/:quiz_id/result
:module_id/student/live 
:module_id/student/history
:module_id/student/feedback 
```
This also doens't apply to any other routes that are not sub-routes of :module_id

**Comment by sohilpandya** [comment]
Hi @stianr, this should now be fixed.

Could you please have a look and close this issue if you are happy.

Thanks

**Comment by stianr** [comment]
This is brilliant - many thanks!
