### ISSUE TITLE
Show quiz questions only shows first two options from each question

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#242]
This seems to have just arisen - it was fine last week. Only the first two options from each question are visible, rather than the full 4.

![image](https://cloud.githubusercontent.com/assets/16817089/19815359/5818647a-9d3a-11e6-8062-06b11d052956.png)

**Comment by franzmoro** [comment]
issue ready for testing on new [staging environment](http://cul-app-staging.herokuapp.com)

**Comment by stianr** [comment]
Fixed.
