### ISSUE TITLE
Codecov stats should be visible on PRs

### ISSUE THREAD

**Issue by franzmoro** [cul-2016/quiz#245]
## Tasks
- [x] update codecov yml
- [x] ignore "containers" + "components" folders

**Comment by iteles** [comment]
@franzmoro @sohilpandya I didn't catch the reason for adding the extra dependency in https://github.com/cul-2016/quiz/pull/246 - would be good to list that in this issue if it's the reason it was added 👍

**Comment by franzmoro** [comment]
@iteles 
- "codecov" devDependency was needed to get the coverage stats
- "react-addon-transition-group" was already in the project but not saved in the package.json. I had a bundling problem :bug: without it (requiring module which wasn't there).
