### ISSUE TITLE
Email verification for lecturers

### ISSUE THREAD

**Issue by iteles** [cul-2016/quiz#248]
As an admin, I must be sure that people signing up as lecturers own the emails they sign up with, so that fake email accounts cannot be used to sign up. As such, I would like to see an email verification step in the application, whereby:
+ [x] An email is sent to the lecturer upon sign up which contains a verification link
+ [x] Clicking on the verification link takes the lecturer to a page with a simple message confirming their email is now verified
+ [x] That lecturer can now log into the application
+ [x] Lecturers that have *not* verified their email **will not be able to log in**

**Comment by iteles** [comment]
@franzmoro @sohilpandya All dwyl projects so far have used [sendemail](https://github.com/dwyl/sendemail#moving-out-of-aws-ses-sandbox-environment) to send emails from applications (this does not solve the verification *link* portion, but *does* solve the sending of the emails themselves).

Please note:
+ [This paragraph](https://github.com/dwyl/sendemail#moving-out-of-aws-ses-sandbox-environment) on getting out of the AWS SES sandbox environment, which I would suggest you **do on day one**.
+ SES has a bounce rate limit (as do all email service providers) so [do not use any fake email addresses in your tests](https://github.com/dwyl/sendemail/issues/49).
  + Have a chat with @roryc89 who has built a bounced email tracker into his latest project - it has been built as a separate module and it would be good to understand how much time would be required to integrate it into another (this) application 
+ This verification email piece of functionality is a perfect candidate to be built as a separate module which is then integrated into your application as a microservice (in a similar fashion to what Rory has built) - very much worth looking into doing this

**Comment by sohilpandya** [comment]
**Current Flow for the lecturer:**
- Lecturer can register via specific url 
  - path to register as a lectuer`register-lecturer-invite-only`
- Once the lecturer signs up, they are taken to the `module-dashboard`

**Comment by franzmoro** [comment]
@stianr 
For now we set up the following "please verify" email message template:

```
Hi lecturer!
 
Thank you for registering as a lecturer!
Before accessing your account, you need to verify your email by clicking on this link **verificationLink**

City University Quiz app http://cul-app.herokuapp.com/
```

The "hi lecturer" part is probably not great, but at the moment we do not have a mandatory username. Potentially we can greet the users who have provided a username, but would need a default greeting for those who don't.

**Comment by stianr** [comment]
@franzmoro Can we just have "Hello!" rather than "Hi lecturer", as the default for no username, and "Thank you for registering as an instructor!" rather than 'lecturer'. (That gives it a broader relevance - lecturer doesn't mean the same thing in the US as UK, and we might have people signing up who won't be using it in a lecturing context.)

**Comment by stianr** [comment]
User story looks good.

**Comment by franzmoro** [comment]
@stianr this issue is now ready for testing on the new [staging environment](http://cul-app-staging.herokuapp.com)

**Comment by stianr** [comment]
Worked for me.

**Comment by stianr** [comment]
(Just to note that the first time I did this I'm pretty sure I didn't click on the verification link but was still able to log in, and when I clicked the link it said it had already been used. Didn't happen again. An out of office message would have been sent in reply to the verification email - could that have done it?)

If this is unexpected, I can test further - I could be wrong - but have run out of email addresses for now...

**Comment by franzmoro** [comment]
@stianr the out-of-office message will not affect the behaviour of this feature.
The emails you used should have been removed from the staging db (I have just now reset it), so that you can use them again for registration.

Can you please confirm that the above behaviour is still happening?

**Comment by stianr** [comment]
Have just registered stianl as lecturer. Was able to log in before the verification email came through. Just to check, I've been using this URL: https://cul-app-staging.herokuapp.com/#/register-lecturer-invite-only to sign up as a lecturer. Is that right?

Tried again, registering stianr as lecturer. Would not allow login without verification.

**Comment by franzmoro** [comment]
the registering link is correct.
the behaviour is odd and, according to our db, the user stianl is verified, whereas user stianr is not. 

you might actually be onto something with regards to the way your email is being processed (i.e. with the auto-reply), although we don't yet understand why that is. We'll investigate further.

**Comment by franzmoro** [comment]
tried out signing up as a lecturer with both hotmail and gmail accounts and set auto-reply on both. got the "user not verified" message on both occasions.

**Comment by franzmoro** [comment]
@stianr has this not worked consistently with the same email address? If so, can you try registering as a lecturer with this same email without auto-reply?

**Comment by stianr** [comment]
The out of office system should only send a single autoreply to a given email. So I doubt it's the issue here. But if you reset the staging database, I can try again with autoreply off.

**Comment by franzmoro** [comment]
This is what we thought as well at first, but we didn't manage to replicate this behaviour.
Anyway, the staging db has been reset. Let us know if the issue persists and, if so, if it happened only with the same email

**Comment by stianr** [comment]
I've tried to register as a lecturer with three city.ac.uk email addresses (and had the out of office message switched off for the main one), all of which let me log in without verification, and with two non-city emails, both of which required verification.

If you reset the database, try registering with my City email address and then logging in straight away - hopefully you'll be able to replicate the behaviour.

**Comment by franzmoro** [comment]
ok, finally replicated it as @stianr said. Here are the first findings:
  - happens:
    - with staging environment (i imagine it would happen in production as well)
    - using any "@city.ac.uk" email, even imaginary ones, to signup

  - does not happen:
    - with localhost environment
    - using hotmail, gmail, and many other commercial and academic domains to signup

**Comment by franzmoro** [comment]
@stianr This should now be fixed.

## Identified cause
Any email to any address with the "@city.ac.uk domain seems to be processed by a bot, which checks for http links (making the requests too). This means the bot was verifying the users automatically.

## Solution
We have removed the "http" from the link in the email, and the auto-verification seems to have stopped.

**Comment by stianr** [comment]
Still able to login without verification when registering as a lecturer with a City email address.

**Comment by franzmoro** [comment]
@stianr sorry, and thank you for the patience.

Apparently the bot took a little longer without the "http://" but still managed to capture the verification url and auto-verify, and had fooled me.
Unless we know more about the bot-logic (we've had to guess this far), or disable this mechanism altogether for the emails sent by this app (if it's possible for the IT department at city uni? other unis implementing such checks would need this as well), we can only propose for **registering lecturers to paste the verification url in the browser**. Would this be ok?

In the meantime the verification url to paste in the browser can be tested (I have successfully with @city.ac.uk accounts, and hopefully it should work for you as well).

**Comment by stianr** [comment]
I think at this stage of development it's most important for it to be as easy as possible, so I'd rather take the risk that people sign up with a fake email that autoverifies than everyone has to manually copy and paste the link. So can we revert to having the clickable link in the message please. (Fwiw, I tried with a UCL email address I have, and it required verification, so it's not all universities that are set up the way City is.)

Hopefully we can fix this later on - presumably most email verification systems would have a similar problem?

**Comment by franzmoro** [comment]
ok. we've reverted to the clickable link.

Follow-up options below, @iteles @stianr 
1. Leave as-is, for time being

2. Bot-proof verification flow (estimate 1d):
  - url in email re-directs to web page (not verifying user yet)
  - user interacts with human-proof test (e.g. a [captcha](https://www.google.com/recaptcha/intro/index.html)) and sends verification request to server.

3. City-uni IT department to prevent scanning urls from the city-uni quiz app email address.

**Comment by stianr** [comment]
Thanks - all working as it was.

I think longer term, passing the query string on the verification email to an interstitial page that just has a button saying "Click here to verify" which then passes the query string on to the verification URL, would deal with the problem - I don't think we'd need to make it bot-proof, as I doubt City's link checker would crawl beyond the URL in the link, and it would make it easier for users. So it should be a fairly quick job. But not one to focus on now.

For reference, when I just tried it the automatic request came from 70.39.157.195. 

Should I leave this open or close now?

**Comment by franzmoro** [comment]
I guess close this and create a new issue referring to point 2 of my comment (or your last comment, I think we're in agreement).
