### ISSUE TITLE
Is the current data (on the production database) valuable?

### ISSUE THREAD

**Issue by franzmoro** [cul-2016/quiz#254]
A modified DB structure is needed to implement new features.

If data is **not so valuable**, we can:
  - implement new db fields
  - wipe the db clean and start fresh with new fields (quick)

If data is **valuable**, we need to:
  - implement new db fields
  - migrate the production db to the new schema at the end of the sprints (would take our focus off of other activities when doing this).

**Comment by franzmoro** [comment]
@sohilpandya @iteles

**Comment by stianr** [comment]
Just checking with the main other user. I'm hoping we can go for wiping everything. Are you wanting to do that immediately?

**Comment by franzmoro** [comment]
Thanks @stianr. We don't need to do it immediately (actually it would be among the last things), but soon enough we will need to plan whether we will be doing it or not.

**Comment by iteles** [comment]
@franzmoro @sohilpandya Also worth having a chat with the Oxford Abstracts team (20 minutes is enough) to understand how they are migrating data with their current, in production postgres app and what the timelines for this might be.

**Comment by sohilpandya** [comment]
Hi @stianr, we've discussed migrations in detail in the following issue #266, we've also provided a potential time estimate for Migration of data as well, we would love to hear if this is something you'd like us to look into or we can go down the route of starting off with fresh databases. 

Thanks

**Comment by stianr** [comment]
I've checked with all the current users, and it's fine to delete all current contents. Please let me know when you're doing it, in case I'm testing or demoing something.
