### ISSUE TITLE
Creation of a Gmail Account and leaving SES sandbox environment

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#257]
We need to create a Gmail account for the Quiz App. This can be linked to the AWS SES, so that all the emails are sent from the newly created account. 

- [x] Gmail Account
- [x] We also need to respond to AWS SES to move us out of the sandboxed environment.

**Comment by iteles** [comment]
👍 Please add the details to our shared google doc (I'm not sure we have one yet!)

**Comment by sohilpandya** [comment]
I have reopened the case for AWS SES, and provided them more information with regards to it, they should hopefully get the account out of a sandbox. Will update here once AWS get back to me. :)

**Comment by franzmoro** [comment]
quiz.cityuni@gmail.com account created, password on google doc

**Comment by sohilpandya** [comment]
Our Amazon SES limit has been increased to 50,000 with a send rate of 14 messages per seconds! 🎉 💥
