### ISSUE TITLE
Students should be able to review the questions and answers

### ISSUE THREAD

**Issue by iteles** [cul-2016/quiz#259]
As a student,
I would like be able to review the questions in the quiz along with the various multiple choice answers,
So that I can use the quizzes as a study guide when I am revising for my exams.

_Note:_ Seeing the correct answer along with the student's answer will be estimated separately. Issue numbers to be linked here when they exist.

**Comment by sohilpandya** [comment]
Student will be able to click the quizzes they've completed
<img width="418" alt="screen shot 2016-12-21 at 11 15 33" src="https://cloud.githubusercontent.com/assets/2305591/21387282/dc38497e-c76e-11e6-9bec-71d4852c51ff.png">

This will redirect them to a new component, where they can view all the questions that are part of the particular quiz. 

**note** We think that showing the correct answer will also be straight forward as it is part of the same query as fetching the list of questions, so we believe we can do that as part of this issue. 

**2 Days**

**Comment by franzmoro** [comment]
issue ready for testing on new [staging environment](http://cul-app-staging.herokuapp.com)

**Comment by stianr** [comment]
Works well.
