### ISSUE TITLE
Students should be able to reveal *their* answer when reviewing questions

### ISSUE THREAD

**Issue by iteles** [cul-2016/quiz#261]
As a student who is reviewing the questions in the quiz along with the various multiple choice answers (see #259 & #260),
I would like to be able to click a button to reveal the **the answer I gave in class** (whether this is right or wrong),
So that I can use the quizzes as a study guide when I am revising for my exams.

_Note: This is an enhancement of #259 and #260 and will need to be time estimated before @stianr can prioritise it._

This will also need to take into account what happens when:
+ The student's answer was correct and was therefore the same as the correct answer
+ The student's answer was incorrect 
+ The student didn't answer the question

**Comment by sohilpandya** [comment]
This is slightly more complicated, as we will need to query for the given user's answer for all the questions in a given quiz. 

We would add an additional **1 day** to the original estimate provided in #259

**Comment by sohilpandya** [comment]
**updated estimate - 1.5 - 2 Days**

- having to create a separate query for students and lecturer (currently in #259, #260 we are using a pre-existing query)

**Comment by stianr** [comment]
Functionality: Did not display question or answers for a question where I did not give a response - it should allow students to review all questions, even those that they did not answer.

Design (perhaps for later): If a student has the right answer, it only highlights the correct answer in green. So if I had a lot of answers right, I wouldn't be sure what it was showing - is it showing my answer, or just the correct answer. Something indicating the user's choice separately from the correct answer would be good. An example from buzzfeed uses ticks for user responses and colours for correct answers: https://www.buzzfeed.com/perpetua/can-you-ace-this-basic-math-quiz-without-using-a-calculator

Apart from that, all working well.

**Comment by stianr** [comment]
Keeping this open for future work, as may want to implement the element where student presses a button to reveal correct answer. At the moment, correct answers are always shown immediately.

**Comment by sohilpandya** [comment]
I'll remove the please-test label from this issue as the original functionality (without the reveal answer) has been tested.

**Comment by stianr** [comment]
Closing, as this is no longer a live issue.
