### ISSUE TITLE
Server Side Authentication with Cookies

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#267]
We've been discussing the best way to tackle the security issue and having server side authentication, and we're thinking of using [Hapi Auth Cookie](https://github.com/hapijs/hapi-auth-cookie)

@iteles we wanted to find out if anyone in DWYL has used this particular module or if you'd recommend we use Hapi-auth-JWT instead of the one above, if similar outcomes can be achieved. 

**Things to look out for**
- Back end will have authentication for all routes by default, we can turn of auth for specific endpoints that do not require it. (`auth: false`)
- At the moment the `cul_id`, `cul_is_lecturer` & `cul_is_cookie_accepted` are being used for front end authentication in React, so we will need to alter the flow so that the front end is now looking for the encrypted versions of this, decrypting them and then storing them in the state. 

**1/2 to 1 day `spike` potentially**

relates to #247

**Comment by sohilpandya** [comment]
Hi @Danwhy, we'd like to get your opinion this particular issue, we're trying to figure out what the best way to solve the server-side authentication flow.

Have you ever users `hapi-auth-cookie` or `hapi-auth-jwt` for server side authentication? (or anything else for that matter)

Which one have you used in the past? or is there one you'd recommend? 

Thanks! :)

**Comment by iteles** [comment]
@tonydaly, seeing as this is a security question, would also be good to get your thoughts here *if* you have some time.

@sohilpandya Good to also get a note here of what problem this issue is solving for posterity.

**Comment by franzmoro** [comment]
### Issue Explanation

Currently, the authentication works with front-end cookies set from the back-end when the user logs in. The rest of the process is dealt with by React-Router. Each authentication-required route currently has a router "on-enter hook".

**Vulnerabilities**:
  - Storing cookies (e.g. user id, is_lecturer) as plain values is a potential vulnerability.
  - Server-side routes (e.g. get quiz answers, get module quizzes) do not have authentication

**Comment by Danwhy** [comment]
I haven't personally had much experience integrating server side auth, but @simonlab used [hapi-auth-jwt2](https://github.com/dwyl/hapi-auth-jwt2) for very basic authentication on the [Science Museum project](https://github.com/TheScienceMuseum/collectionsonline/tree/master/auth). We never had any trouble with it, and of course, it's _very_ well documented :wink:

**Comment by iteles** [comment]
We can also ask @nelsonic to point you in a good direction for this, but he won't be available until mid afternoon

**Comment by nelsonic** [comment]
@sohilpandya if you want to do a hangout on this at some point, just let me know. 👍

**Comment by tonydaly** [comment]
@nelsonic @sohilpandya a hangout would be good, I can do a demonstration of some of the issues I've found.

**Comment by iteles** [comment]
@nelsonic @tonydaly The team is back from the break on Tuesday 3rd January. Are either of you free for a hangout that morning?

**Comment by shouston3** [comment]
Thanks @iteles @tonydaly @nelsonic,

@sohilpandya & I will be looking into hapi-auth-jwt2

**Comment by iteles** [comment]
#277 supersedes this issue, closing.
