### ISSUE TITLE
Students should not be able to signup with a fake email

### ISSUE THREAD

**Issue by franzmoro** [cul-2016/quiz#270]
Currently a student can signup with any email (even non-existing emails).
<s>Do we want to prevent this?</s> **update**: We should check for fake emails first

For lecturers this won't be an issue, as they need to verify with their email.
**update**: *fake lecturer emails will affect our email service*

**Comment by iteles** [comment]
@franzmoro @sohilpandya It's important that students can sign up with any domain email, *but* fake emails will kill our email service! Please see the comment here: https://github.com/cul-2016/quiz/issues/248#issuecomment-267487419

Please speak to @roryc89 about whether we can re-use his bounce rate checker and blocker.

**Comment by sohilpandya** [comment]
We can try to use the following module to help us determine whether an email is valid or not - https://github.com/nmanousos/email-existence

This would help with bounce rates.

The idea would be to reject the signup process if the email does not exist according to the module. 

**3 Hours**

**Comment by iteles** [comment]
@sohilpandya Beware of https://github.com/nmanousos/email-existence/issues/28

**Comment by sohilpandya** [comment]
@iteles ahh, definitely not a reliable module...

**Comment by sohilpandya** [comment]
An alternative that has been suggested:
- Keep track of all the emails that have been bounced by SES, blacklist these emails and don't allow them to register using the same email again. 

We feel that there is a lot of work involved for this to take place. We are not thinking of solving this issue by going down this avenue.

**Comment by franzmoro** [comment]
There are email verification services, such as [mailboxlayer](https://mailboxlayer.com). The free version allows up to 1,000 requests, but this might get us asking what should happen after the 1,000 mark (i.e. we don't check for them anymore, otherwise the whole signup service would go down).

**Comment by sohilpandya** [comment]
I've done some quick research and found that AWS SES keeps to a 5% bounce rate. that means for our account which has a limit of 50,000 emails/day, the number of emails that will have to bounce before our account is put under probation is 2500. 

I don't think that we need to implement any of the two options that we have been discussing above.

**Comment by franzmoro** [comment]
This leaves us with a flawed logic in our server. A bounced email should not lead to a user signup.

**Comment by franzmoro** [comment]
@iteles , although it has a "*technical*" label, someone should probably user-test this, right? ( @sohilpandya and I have, but best if someone else does too)

**Comment by iteles** [comment]
@franzmoro You're right, this is testable by our PO, so he should test it when it is ready!

**Comment by hhsadiq** [comment]
@sohilpandya @franzmoro Hey guys, can you tell how you guys were able to solve this issue (beside using paid service)? I am working on similar task and want to figure out fake/non-exisitng emails.

**Comment by sohilpandya** [comment]
@hhsadiq thanks for taking a look, we use **validator** module for checking invalid emails :) https://www.npmjs.com/package/validator

**Comment by vergun** [comment]
@hhsadiq

**Comment by iteles** [comment]
Closing this technical issue, resolved as per the above 👍
