### ISSUE TITLE
Researching hapi-auth-jwt2

### ISSUE THREAD

**Issue by shouston3** [cul-2016/quiz#277]
relates to #247 
We will be looking into hapi-auth-jwt2:

- [x] setup the basic layout for authentication using hapi-auth-jwt2
- [x] create an example route with auth 
#

**Comment by sohilpandya** [comment]
We've managed to get a simple version of `hapi-auth-jwt2` up and running on the app.

- We've replaced authenticate-user with authenticate-user-jwt, this has also been converted from a handler to a plugin as we needed access to the server.app.


Our plan is to use `redis` to store the session id and set an expiry time of 2 months for the cookie & redis hash.

**Comment by iteles** [comment]
Closing this technical issue, researched and resolved as per the above 👍
