### ISSUE TITLE
Setup Redis for authentication token caching

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#279]
relates to #247 

- [x] setup redis on the app (locally)
- [x] store user session token as a hash `user_id:hash`
- [x] set expiry for both the token and hash
- [x] setup redis for circle_ci and Heroku

**Comment by shouston3** [comment]
**Update for the day**:

We've managed to get redis up and running, but testing has proven to be quite painful.
 - It took us an hour or two to find a bug with initialising redis and not exiting out of the pretest script.
- We started tackling the endpoint tests, but have come across an issue where it is difficult to simulate authentication for every endpoint.

Unfortunately for us our endpoint tests are split into different files and we have had no luck exporting the token once created by the 'simulate authentication' test.

#### Tomorrow

We are planning to set a token in redis in the `init.js` file (run by the pretest script) we will then know the token to use when authenticating and can test all of the endpoints.

**Comment by sohilpandya** [comment]
**Just some additional details with regards to the above**

**Setting up Redis**
Initially, we tried to attach the `redisClient` to the `server.app` but that proved to be difficult to manage especially with the way the `tests` are laid out in its current form, hence we moved away from it and are now exporting a client which we instantiate and quit every time it is used.

**Comment by sohilpandya** [comment]
@shouston3 Looks like having the headers here - https://github.com/cul-2016/quiz/blob/jwt2/test/integration/endpoints/abort-quiz.test.js#L29 is causing the test to return a 500, if you remove that line and then run the test, we get the 401 error. 😨 

so for some reason, adding the header in option is causing the test to return with a 500...

**Comment by sohilpandya** [comment]
Implemented this with #247
