### ISSUE TITLE
Node version and slow test transpiling

### ISSUE THREAD

**Issue by shouston3** [cul-2016/quiz#281]
#### Why would we want to?

At the moment we are transpiling the tests to es6 which also are run on every commit.

Upgrading will allow for faster tests, simpler scripts (without transpiling) and more consistent syntax on the front and back end (use es6 everywhere).

**Comment by sohilpandya** [comment]
After some research (@shouston3), updating to 6.9.1 and updating all the dependencies does not cause any breaks in code. 

I suggest @shouston3 create a PR, then we review it before merging in if all works ok? 

@franzmoro @Danwhy @iteles Does that work?

**Comment by sohilpandya** [comment]
**Todo**
- [ ] update node and dependecies locally
- [ ] update node version in package.json, circle_ci, Heroku`?`

**Comment by Danwhy** [comment]
Upgrading to the most recent stable version sounds like a good idea to me, and if it fixes some issues then all the better

**Comment by sohilpandya** [comment]
@shouston3 I won't be in the office on Friday Morning, so that might be a good time to tackle this? I'll be back by lunch so that might be a good thing to tackle on your own if you are happy to do that?
