### ISSUE TITLE
Student history

### ISSUE THREAD

**Issue by franzmoro** [cul-2016/quiz#289]
Student history is loaded when on "feedback" tab. Is viewable when clicking on "history" tab (from "feedback" tab).
<img width="925" alt="screen shot 2017-01-05 at 10 13 01" src="https://cloud.githubusercontent.com/assets/13413717/21674813/bb5f20de-d32f-11e6-8e40-40c2911744ee.png">

Disappears if refreshing on "history" tab
<img width="924" alt="screen shot 2017-01-05 at 10 13 11" src="https://cloud.githubusercontent.com/assets/13413717/21674817/bd47ab5a-d32f-11e6-912b-b2ca25b1a8e9.png">

### Suggestion
- use ```componentDidMount```lifecycle or router based logic (on history)

**Comment by sohilpandya** [comment]
No longer applies, views have been changed.
