### ISSUE TITLE
Testing refactor

### ISSUE THREAD

**Issue by shouston3** [cul-2016/quiz#290]
#### **Problem**
There is no way to isolate tests
Currently the globbing pattern in the `test` script in the package doesn't allow for selcting individual files to run
#### **Solution** (30 min time estimate)
Implement a test runner which will require files in instead allowing for better test isolation

#### **Problem**
Server transpiling and file structure
At the moment the file structure isn't clear how tests are split up
We also transpile everything which isn't needed
#### **Solution** (1 hour time estimate)
Proposed new scripts:
```json
"scripts": {
  "test:front": "tape -r babel -require ./test/utils/jsdom.js 'test/front/runner.js'",
  "test:back": "tape test/back/runner.js",
  "test": "npm run test:front && npm run test:back"
}
```
Proposed new file structure:
```
├── test
    ├── utils
    ├── front
      ├── front
        runner.js  <---- require all front end tests
        actions/
        reducers/
        lib/
    ├── back
       runner.js  <---- require all back end tests
       endpoints/
       database/
```

#### **Problem**
Not Orthogonal (not independent) tests. Currently we cannot skip tests without breaking others.
This makes debugging and isolating the problem much more difficult
Currently we only flush the database before running the tests
#### **Solution** (2hr)
Flush the database (and clear any cache) before every test which relies on any initial configuration

#### **Problem**
Pre test script doesn't allow for a open connection to be set up and is causing us a lot of problems with redis
#### **Solution** (1hr)
Get rid of the pre test script
* Import the initialised server
* Import the postgres client
* Import the redis client

#### **Addition** (30mins)
Attaching the postgres and redisCli to the `server.app` object

#### **Typical endpoint test**
```js
let potentiallyGlobalToken;

test('typical database test', (t) => {
  flushDb() // flush both redis and postgres databases
    .then(() => setUpSchemaConfigForSubsequentTest())
    .then(() => simulateAuth())
    .then((potenitallyNeededToken) => {
      potentiallyGlobalToken = potenitallyNeededToken;
      server.inject('/endpoint', options)
        .then((res) => {
          t.plan(n);
          t.equal(res.thing, result);
        });
    });
});
```

Order to fix:
- [x] File structure and transpiling and test runner (the rest will be faster and easier)
- [x] Orthogonal
- [x] Pre test
- [x] Server refactor
- [x] Database fixes
- [ ] Stub email requests

Relates to #247 
Relates to #287 
Relates to #279

**Comment by shouston3** [comment]
@Danwhy @nelsonic @franzmoro 

Could you please have a look at the above and let us know what you think of the architectural changes @sohilpandya and I are planning to implement.

**Comment by franzmoro** [comment]
I think it's all great. Bear in mind that I recall some tests being dependent on others, so if you flush the db each time, you will have to remove those dependencies (which would also be good).

**Comment by sohilpandya** [comment]
We've implemented the changes for test-refactor.

**Comment by nelsonic** [comment]
well done for improving this gents! 😍
