### ISSUE TITLE
Implement https for every request

### ISSUE THREAD

**Issue by shouston3** [cul-2016/quiz#300]
- [x] Add a plugin to redirect every incoming http request to https as implemented in [this module](https://github.com/bendrucker/hapi-require-https/blob/master/index.js)
 - [ ] Setup ssl on heroku and codecov
 - [ ] Add ssl setup instructions to the README

As raised by @tonydaly in #247

**Comment by sohilpandya** [comment]
**update** 

We were in the middle of implementing SSL for heroku but found this:
```
SSL Endpoint is only useful for custom domains. All default appname.herokuapp.com
domains are already SSL-enabled and can be accessed by using https, for example, 
https://appname.herokuapp.com.
```

So we don't need to follow through with https://github.com/cul-2016/quiz/commit/d15e34c5a5082102756e9c393bc3e9c319de253f where we implement ssl. 

Will update the branch and only follow through with `hapi-require-https`

**Comment by shouston3** [comment]
Closing, will reopen a separate issue for when we need further ssl implementation.
