### ISSUE TITLE
Students History view not showing all the question

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#316]
When a student views quiz history for a quiz where they haven't answered all the questions, it hides the question completely as shown below. 

related to #261 
![screen shot 2017-01-11 at 12 15 28](https://cloud.githubusercontent.com/assets/2305591/21852702/0ad736de-d80c-11e6-821d-e495b4518915.png)

**Comment by iteles** [comment]
Is this now in `please-test` @sohilpandya ?

**Comment by sohilpandya** [comment]
@iteles we have not yet tackled this bug @iteles. I accidentally added the in-review bug when I created the issue.

**Comment by iteles** [comment]
Ah right, this is the student view - I got this mixed up with the lecturer bug we fixed where not all the *answers* were shown 👍

**Comment by stianr** [comment]
Have still seen it missing questions, but that may be because one of the questions didn't have a correct answer set #406. Will review once that is complete.

**Comment by stianr** [comment]
Works for me.

**Comment by iteles** [comment]
@stianr Are we happy to go ahead and close this?
