### ISSUE TITLE
`authenticate` onEnter redirects to `app-loading` which hangs

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#317]
When the app does not have the `user` State, it redirects the user to `app-loading` this is hanging. (most likely due to the changes we've made,  need to debug)

**Comment by sohilpandya** [comment]
**issue** using a cookie that no longer existed after the security implementation

**resolved**

**Comment by sohilpandya** [comment]
`app-loading` still hangs at times. Need to spend some time debugging and also redirecting user to `/dashboard` if they are taken to app-loading should solve the issue.

**Comment by sohilpandya** [comment]
I've just restructured the code, this should no longer be an issue.

**Comment by iteles** [comment]
Done! 👍
