### ISSUE TITLE
Merge `Survey` with latest staging version

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#318]
I'll be spending some time merging this locally, as we have made a lot of changes in the server-side and tests, there are bound to be some conflicts that need to be resolved. 

Will updated once that is completed here.

**Comment by sohilpandya** [comment]
Changes made by Franz for #263 in PR #286:

`saveStudentResponse` - now takes an additional argument - `survey_id`

**Comment by sohilpandya** [comment]
**update**
merge conflicts now fixed, just fixing the failing/hanging tests now.

**Comment by sohilpandya** [comment]
I have updated and merged Franz's branch with the latest staging.

**Comment by iteles** [comment]
Done 👍
