### ISSUE TITLE
Ability to Preview a Quiz

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#321]
As a lecturer, 
I would like to be able to preview a quiz without running a Live Quiz.

**Problem**
At the moment the Lecturer can Abort a quiz, but if the lecturer ends the quiz (accidentally) they are unable to re-run the quiz. 

**Solution**
Add a Preview button so that the lecturer can run a quiz without having any side-effects

**Comment by iteles** [comment]
Worth listening to the recording as a reminder of what our agreed solution on this was!

**Comment by sohilpandya** [comment]
@iteles I'll find the part where this is being discussed and let everyone know agreed solution.

**Comment by sohilpandya** [comment]
**1 hr 21 mins on the call**

**discussed having the option to re-run the quiz (not in the scope of this issue)**:
- Allow lecturer's to rerun the quiz
  - do not touch existing students responses when re-running the quiz, Only add/overwrite responses

As Suggested in the **solution** above, we can add an additional button called Preview Quiz, which will only appear for quizzes that have not been run before. Once the Lecturer gets to the end of the quiz, we will run our `Abort Quiz` function.
- Create new routes for preview Quiz
- Display `Abort Quiz` button at the end of quiz preview.

**Comment by iteles** [comment]
PR currently deployed to staging to allow @stianr to have a quick review of the feature prior to Monday.

**Comment by sohilpandya** [comment]
This issue can be closed once the bug related to it has been tested https://github.com/cul-2016/quiz/issues/439

**Comment by stianr** [comment]
Bug seems to be fixed, so closing this.
