### ISSUE TITLE
Quick start instructions not working

### ISSUE THREAD

**Issue by shouston3** [cul-2016/quiz#329]
I'm not sure if it's a recent change, but following the quick start instructions logs the error:

`Uncaught error: options.verifyFunc is not a function`

For every request to any endpoint with auth.

Are you getting this @sohilpandya ?

**Comment by shouston3** [comment]
Thanks @sohilpandya, enviro variable issue.

**Comment by hlibco** [comment]
I had the same problem. The variable name that contains the issuer in the .env file had a typo. The error should be more descriptive though.
