### ISSUE TITLE
'Please enter a valid email address' for valid email address

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#337]
When attempting to register as a student, I enter a valid email address, but am unable to register as the email is treated as invalid. I have tested this with several valid email addresses including one that has never been used on this system and all give the same issue.

![image](https://cloud.githubusercontent.com/assets/16817089/22002072/ef31cae6-dc40-11e6-8df4-1f00eac395f7.png)

**Comment by sohilpandya** [comment]
Hi @stianr, this should be fixed on the [staging version now](https://cul-app-staging.herokuapp.com).

Could you please test it. Thanks

**Comment by stianr** [comment]
Great - working.
