### ISSUE TITLE
Unable to webpack build with font-awesome

### ISSUE THREAD

**Issue by shouston3** [cul-2016/quiz#343]
Seems to only be happening on my computer (out of mine and @sohilpandya 's)

Steps to Replicate:
 * Follow the [startup instructions](https://github.com/cul-2016/quiz#quick-start)

Webpack throws error:

![screen shot 2017-01-17 at 14 38 03](https://cloud.githubusercontent.com/assets/15983736/22024663/97741a5c-dcc2-11e6-927f-d907161b9bae.png)

The server can't find the bundle because webpack is complaining and won't build.

Current solution is to not use font awesome. (Remove it from the `webpack.config.js`).

**Comment by iteles** [comment]
@shouston3 Who are we expecting to test this?

**Comment by shouston3** [comment]
Ah I forgot to assign, I was thinking (at least initially) @sohilpandya (from a recloned repo).

But actually anyone would be good.

**Comment by iteles** [comment]
Closing this technical issue, removed 👍
