### ISSUE TITLE
CSS questions for live-quiz

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#373]
This is the current state of the page.

![screen shot 2017-01-23 at 17 56 14](https://cloud.githubusercontent.com/assets/2305591/22216060/70dce216-e195-11e6-8f7b-bba621cf93c9.png)

**TODO:**
- [ ] change colour of submut button. (also it's background color.

**Comment by stianr** [comment]
Looking good! Note #342 - perhaps you could estimate time for removing submit button and changing functionality of choosing an option to choose-and-submit. Relatively high priority, given how much it would improve flow for students.

**Comment by sohilpandya** [comment]
Thanks for the feedback on the design @stianr. It'll take roughly T4h to make the changes related to removing the submit button and having the user's choice submitted as soon as they select the option.

**Comment by iteles** [comment]
Closing this technical issue as complete 👍
