### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#374]
At the end of the project we will need to have the site accessible via a simple URL rather than the herokuapp.com URL it is currently on. So I'm just raising this as an issue to make sure we talk about those practicalities before the project ends.

**Comment by stianr** [comment]
I think we should do this now. I have registered quodl.co.uk, quodl.com. and quodl.uk. At the moment I am only using quodl,co,uk to redirect to the staging version on heroku (which is fine for our purposes). Presumably we now need to move the staging version to the main app site, and then give me instructions on setting up redirection from quodl.co.uk.

I have a meeting with a user on Tuesday afternoon, so would be ideal to get this done today, or at least by Tuesday lunchtime.

**Comment by iteles** [comment]
👍 I'm on writing this today!

**Comment by iteles** [comment]
@stianr 

Please add the following records to your DNS:
+ For quodl.co.uk:
  + `CNAME` record, name = `www`, DNS = `www.quodl.co.uk.herokudns.com`

**Comment by stianr** [comment]
I'm doing this via a gui on uk2, 

![image](https://cloud.githubusercontent.com/assets/16817089/22932282/3eb74d9a-f2bf-11e6-8e32-31e2c6ad3ac5.png)

I've updated cname - is that right? Do I also need to update the name servers, or is that it?

**Comment by iteles** [comment]
@stianr This should be it! I've done this for a test website as well to confirm. 

Takes a few hours (up to 24h) to propagate, depending on your provider

**Comment by stianr** [comment]
Great - thanks! Much less painful than I imagined. Will check tomorrow.

**Comment by iteles** [comment]
@stianr I think this is currently redirecting.

Could you try adding an `ALIAS` or `ANAME` record?
You'd want to have the name either empty or as `@` with the target DNS as above.

https://devcenter.heroku.com/articles/custom-domains#configuring-dns-for-root-domains

**Comment by stianr** [comment]
I put a redirect in separately a few days ago, so I'm guessing that's what's causing the redirect - quodl.com and quodl.uk don't have redirects (and they just give the uk2 holding page).

Can't see any reference to ALIAS or ANAME on the DNS configuration pages. This is what I'm able to change:

![image](https://cloud.githubusercontent.com/assets/16817089/22938840/e0d368ce-f2d4-11e6-8c58-b1ee182484a4.png)

**Comment by stianr** [comment]
As it doesn't seem to have worked (yet), I wanted to check that if for today I redirect students to cul-app.herokuapp.com, that will have the same effect (albeit with the heroku URL visible) as what we're trying to do here. Essentially, can students register and complete their first quiz on cul-app.herokuapp.com and then later log in and see their results when the quodl.co.uk redirect works?

**Comment by iteles** [comment]
Yes, absolutely!

I've emailed our own domain provider to confirm things haven't changed since I did this for the dwyl.io domain as well

**Comment by stianr** [comment]
Looks like DNS has propagated, as now www.quodl.co.uk give a DNS error whereas quodl.co.uk redirects as per my setup on uk2. 

Please keep me updated on this, as it would be great if it could be sorted before tomorrow's session. But not crucial if it can't. Also, can we have everything set up to point to heroku rather than just www - so that if someone enters http://quodl.co.uk, that works in the same way as http://www.quodl.co.uk.

![image](https://cloud.githubusercontent.com/assets/16817089/22980078/57f1d614-f390-11e6-9bb7-fbc68088e957.png)

**Comment by iteles** [comment]
@stianr I'm following up with my hosting provider as the same thing has happened on my side.
I'm not sure why this is happening yet as it's *exactly* the same setup we have for dwyl.io

In terms of having everything pointing to heroku, you just need to contact your service provider and as for the IP address so that you can add a forwarding `A` record where the name is `@` (the root domain). This will alias  http://quodl.co.uk to http://www.quodl.co.uk.

**Comment by iteles** [comment]
@stianr The issue with the test site I'm using is that it's creating a malformed URL so I've now opened a ticket with heroku. The same seems to be happening with quodl so I'll let you know as soon as I hear back!

**Comment by stianr** [comment]
@iteles great - thanks!

**Comment by iteles** [comment]
@stianr Could you try changing that target DNS to `cul-app.herokuapp.com` instead of `www.quodl.co.uk.herokudns.com` please?

**Comment by stianr** [comment]
@iteles I did that last night, and nothing yet - may still be propagating, though I did set TTL to 1 hour for two of the domains a day or two ago.

**Comment by iteles** [comment]
I've opened an urgent ticket with heroku, so sorry this is taking longer than expected, it's usually a click-and-go operation that takes 5 minutes!

**Comment by iteles** [comment]
@stianr When I use curl www.quodl.co.uk on the command line, it's not coming back with any CNAME records, could you please add a screenshot of the latest one here?

**Comment by stianr** [comment]
@iteles This is how it's currently set for quodl.co.uk (and has been over the weekend):

![image](https://cloud.githubusercontent.com/assets/16817089/23122083/ba078506-f75a-11e6-87f5-4c2361a8e8f8.png)

**Comment by stianr** [comment]
If it's something at my end, I can raise a ticket with my providers.

**Comment by iteles** [comment]
@stianr Our reply from heroku and question at the end - could you please confirm?

There appears to be something strange going on with the DNS resolution here as we are seeing different results from http://zone.vision/#/www.quodl.co.uk to running dig from our individual machines.

```shell
$ dig www.quodl.co.uk

; <<>> DiG 9.8.3-P1 <<>> www.quodl.co.uk
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 40371
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;www.quodl.co.uk.       IN  A

;; AUTHORITY SECTION:
quodl.co.uk.        1799    IN  SOA dns1.uk2.net. hostmaster.uk2.net. 1487283419 86400 7200 3600000 86400

;; Query time: 126 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Feb 21 11:51:12 2017
;; MSG SIZE  rcvd: 92
```
**Can you clarify which DNS provider you are using and whether you have changed records recently?**

**Comment by stianr** [comment]
Trying to find an answer for this, I stumbled on some instructions for solving the problem. For UK2, the CNAME name entry needs to be www.quodl.co.uk rather than www. It is now working with www,quodl.com. Current issue is that redirecting to cul-app.herokuapp.com gives a security alert:

![image](https://cloud.githubusercontent.com/assets/16817089/23172051/6a568e24-f84c-11e6-9b99-acbf66d1abe6.png)

You should now see it updated on Zone Vision. I've tried using www.quodl.co.uk.herokudns.com for quodl.co.uk, to see if that corrects the https issue, but it doesn't seem to resolve the DNS:

![image](https://cloud.githubusercontent.com/assets/16817089/23172167/c870885c-f84c-11e6-9b8d-4e3d2a23c84c.png)

**Comment by stianr** [comment]
![image](https://cloud.githubusercontent.com/assets/16817089/23172306/411baca0-f84d-11e6-8b25-3bd6344742ea.png)

**Comment by iteles** [comment]
@sohilpandya @shouston3 Is there anything in the app config that is forcing the redirect to `https` instead of `http`?

**Comment by shouston3** [comment]
Yes, [here](https://github.com/cul-2016/quiz/blob/staging/server/plugins/index.js#L4) we are forcing any `http` requests to redirect to `https`
Using [this](https://github.com/bendrucker/hapi-require-https) module
Would you like this changed?

**Comment by stianr** [comment]
(For more, see #300.)

**Comment by iteles** [comment]
In that case we'll need you to confirm whether this is a security requirement for this iteration  @stianr and if so, you'll need to purchase an SSL certificate to ensure this error message disappears

**Comment by stianr** [comment]
If it's a $15/mo one like here 
https://elements.heroku.com/addons/expeditedssl
Then yes let's do it. If it's going to be more will need to look into it. Please advise as to what's required.

**Comment by iteles** [comment]
@shouston3 @sohilpandya Let's activate expedited SSL for now and confirm this is the issue.

We're working on some documentation for a longer term solution 👍

**Comment by shouston3** [comment]
@stianr, if you are happy to go with expeditedssl then the following steps should set up expeditedssl:
* From the link you posted above: https://elements.heroku.com/addons/expeditedssl
* Click the Install link here: 
![screen shot 2017-02-23 at 15 00 37](https://cloud.githubusercontent.com/assets/15983736/23264369/00cec348-f9d9-11e6-8954-005690689fdb.png)
* Select 'cul-app', then continue
* Click 'provision' on the window that follows, here:
![screen shot 2017-02-23 at 15 03 23](https://cloud.githubusercontent.com/assets/15983736/23264467/4c0c7b2a-f9d9-11e6-9af4-2b8315001b27.png)
* Then after choosing the domain which you would like to have ssl set up on and going through the approval process, it should be installed for that domain

I found [this video](https://www.youtube.com/watch?v=OcyR7Yus4pc) explains the steps to take quite well

Let me know if there are any issues with this setup

**Comment by iteles** [comment]
@shouston3 Sohil and I were also just discussing Open SSL as a temporary measure - just thought I'd note it here

**Comment by stianr** [comment]
Success! www.quodl.co.uk now working as it should - many thanks @shouston3.

**Comment by iteles** [comment]
@stianr Excellent!

Thanks for the info @shouston3 :tada:
