### ISSUE TITLE
Student result CSS 

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#383]
Look like: 
![screen shot 2017-01-26 at 19 18 00](https://cloud.githubusercontent.com/assets/2305591/22346504/4dc17c24-e3fc-11e6-9d25-c1c8918ae1f6.png)

Had to redo as Sam couldn't find the CSS for it. 😢  Looking good now 👍

**Comment by stianr** [comment]
See #399 - no longer displays any trophies that are awarded. But note discussion - may need to leave trophies for now.

**Comment by stianr** [comment]
‘See my answers’ should be changed to ‘Finish’, which would return to module overview page as before. We don’t want the default to be for students to look through the answers ahead of the lecturer talking through them – would reduce learning opportunities, and create a less coherent experience.

**Comment by stianr** [comment]
Please could you change "You score" to "You scored:"

**Comment by stianr** [comment]
Still needs bronze trophy for 0% (see #409)

**Comment by sohilpandya** [comment]
This has been addressed and can be tested on staging.
