### ISSUE TITLE
Lecturer Add Module CSS

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#385]
Looks like: 
<img width="1466" alt="screen shot 2017-01-27 at 00 18 32" src="https://cloud.githubusercontent.com/assets/2305591/22356030/45305af6-e426-11e6-9b53-17c846067f03.png">

**Comment by stianr** [comment]
![image](https://cloud.githubusercontent.com/assets/16817089/22403710/9e8e402a-e617-11e6-9516-ea0d83edb937.png)

On Chrome at least, font colour for the silver medal thresholds is same as background so can't be seen.

**Comment by iteles** [comment]
Similarly, the 'This code already exists' text can also not be seen.

**Comment by sohilpandya** [comment]
Updated styling to reflect the above comments.

**Comment by stianr** [comment]
Looks good. Currently has "Medals" as both heading and subheading, since removing trophies - could you change the subheading to "Set the scores needed for different medals".

**Comment by sohilpandya** [comment]
Updated the heading as suggested above.
