### ISSUE TITLE
Lecturer Leaderboard CSS

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#388]
Looks like
![screen shot 2017-01-27 at 11 17 02](https://cloud.githubusercontent.com/assets/2305591/22369165/351ce1d2-e482-11e6-83b2-1e97b770c021.png)

Had to apply css directly to `table` element. Can be refactored at a later stage.

**Comment by stianr** [comment]
Text would be hard to read on an HD projector from the back of a lecture hall. It would work better if the leaderboard was scaled to take up a greater horizontal proportion of the screen, with font size increased accordingly.

Medals for column headings and counts for each student in those columns need to be aligned.

Wording: Change 'Raw' to 'Score'

**Comment by iteles** [comment]
25 minutes estimated for this change.

**Comment by sohilpandya** [comment]
Updated:

- changed font size to 16px for all the text and increased table size as well as addressing the comment above. 
<img width="971" alt="screen shot 2017-02-03 at 17 05 00" src="https://cloud.githubusercontent.com/assets/2305591/22600811/1ae1557a-ea34-11e6-879a-da56f977c42d.png">

**Comment by sohilpandya** [comment]
The leaderboard on a screen resolution of 1440 x 900 is significantly bigger than at a resolution of 1920 x 1200. We shouldn't have an issue with the size of the font on normal resolution screens. (unfortunately, screenshots at the two different resolutions still show up as the same from my computer (need to be present to see the size change)
<img width="917" alt="screen shot 2017-02-07 at 12 26 08" src="https://cloud.githubusercontent.com/assets/2305591/22691084/a16d5f90-ed30-11e6-85f7-a10df08c2525.png">

**Comment by stianr** [comment]
Looks good!
