### ISSUE TITLE
Trophies not accurately awarded

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#398]
When I register as a student for the first time and join a module, the first time I visit the module page the trophies are shown as 1/4, rather than 0/4.

When I complete a quiz that I score 100% for, I should have been awarded 2 trophies - one for completing the first quiz, and one for getting 100% in a quiz. When I return to the module overview page, I still have the 1/4 trophies I had when I first logged in.

**Comment by stianr** [comment]
See #399, as it will not need to be updated if we drop the trophy mechanics for now.

**Comment by iteles** [comment]
@stianr This was closed in our latest round of work on trophies, could you please confirm it is now working?

**Comment by stianr** [comment]
Yes - seems to be working as it should with the new badges.
