### ISSUE TITLE
Trophy System

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#399]
At the moment, the trophy system isn't working well. This is partly my fault - I didn't catch the implications of the changes to the module overview or leaderboard pages when talking the redesign through with Harry. The main issues are:
- Students no longer see which trophies they've been awarded - only the number that they have - so they can't work out what they need to do to get all four.
- Students no longer see whether they have been awarded any trophies at the end of a quiz.
- Lecturers no longer see the trophies on the leaderboard page. This means they can't discuss performance and award prizes based on students collecting all four trophies (which is what I did last term). 
- There are bugs in the trophy awarding logic (see #398).

I think we have two option here:
- Quickly update the pages re the first three issues, so they retain the trophy information that they had before (i.e., add column(s) to the leaderboard to show trophies either grey or yellow depending on whether they've been awarded yet, as before; have a popup on the trophy icon on module overview page showing the student's status re each trophy; reformatting the end of quiz score page for students so that it has space for and trophies that are awarded).
- Suppress the trophies side of the system for this iteration. Would require (1) hiding the trophy fields for the New Module Page, (2) greying out or hiding the trophy information on the lecturer's module overview page, (3) hiding the - now redundant - 'last quiz' checkbox on the new quiz page, (4) hiding the trophies part of the student's module overview page.

I suspect the second option is going to be substantially quicker, so I think that - sadly - we might be best off hiding the trophies side of things for now, and reinstating it, with the trophy cabinet page, if we can get any more money to take this further. But open to thoughts on this.

**Comment by iteles** [comment]
I think you're right here @stianr, this would be the fastest option for now.

Hiding the trophy fields in the student view and defaulting the trophy ranges to `0` in the lecturer 'New Model' view as well as hiding the fields should take around 2 hours.

**Comment by sohilpandya** [comment]
@stianr can we please close this issue as we've now decided to go down the route of removing any mention of Trohpies for now.
