### ISSUE TITLE
Quit button for live quizzes

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#403]
If the lecturer exits the quiz using 'Quit' button, it no longer cleans up so the quiz is reset as not run (which is what we previously had with 'abort quiz'). Currently, exiting leaves students in the quiz, leaves the 'join live quiz' button active, and if the lecturer starts the quiz again, they jump straight to the current question.

We should either have that functionality reinstated, or if that's going to be time consuming, hide the 'Quit' button.

**Comment by stianr** [comment]
This seems to create a more widespread problem where 'join live quiz' button never switches off for students, even following logout and login, and scoring and quiz flow for subsequent quizzes goes wrong. When lecturer runs another quiz they see:

![image](https://cloud.githubusercontent.com/assets/16817089/22403803/6461b7b2-e61a-11e6-84c3-cb705978f97c.png)

**Comment by stianr** [comment]
Has an issue similar to #400. If I quit and then refresh the module overview page, the quiz is set to already run. It should still be runnable.

**Comment by shouston3** [comment]
@stianr I can't seem to replicate the issue.

Could you list the steps you took to make this bug happen on https://cul-app-staging.herokuapp.com

**Comment by stianr** [comment]
Agree - I can't replicate it now. The current staging version also has styling that wasn't there when I tested, so I'm assuming it got fixed with that update.
