### ISSUE TITLE
Quizzes vs. Surveys

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#404]
On the lecturer module overview there are separate buttons for adding a quiz and adding a survey, but they both seem to bring up the same page, which then has a checkbox to indicate whether it is a survey or not. Some options:
- Use separate customised pages for quizzes and surveys
- If using the same page, pass the 'Is survey?' information from the button press, and hide the checkbox
- Use a single 'Add quiz/survey' button, and let users indicate which it is on the new quiz page.
I guess the third option is easiest?

**Comment by iteles** [comment]
As requested in your email today, let's add in a single button 👍

**Comment by stianr** [comment]
Looks great - much neater.
