### ISSUE TITLE
Quiz setup allows quiz to be run with no correct answer to some questions

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#406]
This may be fixed with styling, but at the moment, the New Quiz section allows lecturers to add and save quiz questions without indicating which answer is correct. If no answer is selected as correct when setting up the quiz, then after running the quiz, when reviewing the questions the lecturer gets stuck on the question with no correct answer.

**Comment by stianr** [comment]
Now seems to be working - safe to close?

**Comment by iteles** [comment]
Please do @stianr
