### ISSUE TITLE
Add Quiz/Survey

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#419]
currently looks like: 
![screen shot 2017-01-31 at 18 02 39](https://cloud.githubusercontent.com/assets/2305591/22477845/8e577612-e7df-11e6-9bdd-1c6812b10248.png)
![screen shot 2017-01-31 at 18 02 31](https://cloud.githubusercontent.com/assets/2305591/22477846/8e5797a0-e7df-11e6-965d-85e4e63d782d.png)

**todo**
- validation check to allow lecturer to save quiz/survey.

**Comment by stianr** [comment]
Looks good.

**Comment by stianr** [comment]
Can we remove the auto-capitalisation of the question text. Lecturers will struggle to include technical terms like fMRI or mRNA, which could be frustrating.

**Comment by stianr** [comment]
Also applies to answer fields.

**Comment by sohilpandya** [comment]
Updated according to the comments above.
