### ISSUE TITLE
Lecturer Member Screens

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#429]
Looks Like: 
![screen shot 2017-02-06 at 15 16 07](https://cloud.githubusercontent.com/assets/2305591/22652703/5bfa34e4-ec7f-11e6-9c9e-dc21ef823642.png)

**Comment by stianr** [comment]
Nice. A couple of edits:

- Most important: It is too easy to remove a student - the clickable area for 'Remove' goes all the way up to the triangle for expanding a student's results. I accidentally deleted a student when I was trying to close their score expansion. In the last version we had an 'Are you sure?' alert before a student was deleted. Can we reinstate that please.
- If I expand a student's score, I can't collapse and hide it again. It would be nice to allow users to expand and collapse at will.

**Comment by sohilpandya** [comment]
Ability to close student's score dropdown, using close icon at top right:
<img width="1025" alt="screen shot 2017-02-10 at 10 55 14" src="https://cloud.githubusercontent.com/assets/2305591/22826162/e84a9d9c-ef88-11e6-95aa-f90628fe1707.png">

Adding alert before removing student:
<img width="1022" alt="screen shot 2017-02-10 at 11 53 02" src="https://cloud.githubusercontent.com/assets/2305591/22826268/70629f0e-ef89-11e6-8b53-3fc830ad37b7.png">

**Comment by stianr** [comment]
Working well for me.
