### ISSUE TITLE
Unable to edit user score

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#432]
Whilst doing the styling for quiz members page, I've come across a bug which leads to the score not being updated for the user. 

**Issue**
https://github.com/cul-2016/quiz/blob/staging/server/plugins/quizes.js#L255-L282

As seen here, we are not getting the user_id from the params, hence the user score is not being updated. 

**solution**

To pass the correct information to the backend and use the user_id to update the score.

**Comment by stianr** [comment]
Works for me.
