### ISSUE TITLE
Lecturer Quiz members

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#433]
Looks like:
![screen shot 2017-02-07 at 12 05 13](https://cloud.githubusercontent.com/assets/2305591/22690433/b6971b98-ed2d-11e6-95cd-937f90282202.png)
![screen shot 2017-02-07 at 12 05 06](https://cloud.githubusercontent.com/assets/2305591/22690434/b6980ac6-ed2d-11e6-9406-97a0e152f02a.png)

**Comment by stianr** [comment]
Works for me.

[Note to self for future iterations - do we want to cap the maximum score at 100%, in case it breaks the scoring and medal/trophy system, or do we want lecturers to have that flexibility to award extra points?]
