### ISSUE TITLE
CSS Login/Register/Forgotten/Reset Password

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#437]
**Login and Register for lecturer looks like:**
![screen shot 2017-02-07 at 15 31 05](https://cloud.githubusercontent.com/assets/2305591/22697916/d8a7259e-ed4a-11e6-970a-9b529ffd621a.png)
![screen shot 2017-02-07 at 15 30 57](https://cloud.githubusercontent.com/assets/2305591/22697915/d895ce8e-ed4a-11e6-9ff8-90ec8c1d0355.png)

**Comment by sohilpandya** [comment]
Forgotten and Reset Password Screens:
![screen shot 2017-02-07 at 16 37 30](https://cloud.githubusercontent.com/assets/2305591/22700985/40c151f0-ed54-11e6-9a0b-7c9539006af0.png)
![screen shot 2017-02-07 at 16 37 22](https://cloud.githubusercontent.com/assets/2305591/22700988/40c6194c-ed54-11e6-9915-14816f4459f3.png)
![screen shot 2017-02-07 at 16 18 02](https://cloud.githubusercontent.com/assets/2305591/22700987/40c4508a-ed54-11e6-94d8-8a826edcf4e7.png)
![screen shot 2017-02-07 at 15 43 42](https://cloud.githubusercontent.com/assets/2305591/22700989/40cb98cc-ed54-11e6-8c8d-ee4a7aa2070b.png)
![screen shot 2017-02-07 at 15 43 34](https://cloud.githubusercontent.com/assets/2305591/22700986/40c43618-ed54-11e6-87ef-8323e16f8e7e.png)

**Comment by stianr** [comment]
Just to check what's going on here, it looks like lecturer and student logins are not selective (e.g., lecturer can login via student page), and they have the same styling - is that right? 

Register for lecturer presumably has separate URL as before, but the same styling as register student.

**Comment by stianr** [comment]
Reset password looks good and works well.

**Comment by stianr** [comment]
Login and register pages on desktop would work better if centred in the screen - particularly for register page, lots of empty space at the top, and then you have to scroll down to see the whole form.

**Comment by stianr** [comment]
![image](https://cloud.githubusercontent.com/assets/16817089/22736351/9bcd1268-edf5-11e6-9cff-3d59d5812589.png)

**Comment by stianr** [comment]
(Applies to both student and lecturer versions of screens.)

**Comment by sohilpandya** [comment]
@stianr that would be different to the design specs, I'm happy to make the above change and center it all, but it'll take me around T25m to make the changes. Please let me know if you'd like me to make them.

Thanks.

**Comment by stianr** [comment]
Would it be possible to collate all the small things that I've raised and anything else remaining, so I can prioritise the use of the remaining time on the project? I can then advise.

**Comment by stianr** [comment]
Actually, probably easier if I do it, and you estimate time. Will open a new issue with all these in.

**Comment by sohilpandya** [comment]
Looks like this after the changes made for #449 : 

<img width="677" alt="screen shot 2017-02-10 at 09 34 38" src="https://cloud.githubusercontent.com/assets/2305591/22822273/9e3c9a64-ef76-11e6-9d40-e01cd6ecc160.png">
<img width="571" alt="screen shot 2017-02-10 at 09 34 29" src="https://cloud.githubusercontent.com/assets/2305591/22822274/9e40271a-ef76-11e6-9763-cd815988471f.png">

**Comment by stianr** [comment]
Crucial thing would be on a desktop browser resolution (e.g., 1920 x 1080), is the login always displayed centrally on the screen.  The current login page always has a vertical scrollbar, no matter what the resolution, and the register page has a lot of space above the register form and then requires scrolling to see the bottom. As these are the first pages that lecturers see, it would be good if desktop users see the whole form displayed centred vertically in the middle of the screen, with no scrollbars unless low screen resolution requires it.

**Comment by sohilpandya** [comment]
I've made the changes and the screen looks like this when the resolution of the screen is **1680 x 1050** 
<img width="1680" alt="screen shot 2017-02-10 at 10 17 02" src="https://cloud.githubusercontent.com/assets/2305591/22823164/59356a5a-ef7a-11e6-82c6-64bd67077df2.png">

No scrollbars at this resolution so it will be fine at 1920x1080

**Comment by stianr** [comment]
Great - looks good. Doesn't seem to be on staging version yet, so ignore what I said - was referring to that.

**Comment by sohilpandya** [comment]
@stianr I'll update you when all of the changes are on staging so that you can test them out again. 👍
