### ISSUE TITLE
Preview Quiz - sets the quiz as run. 

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#439]
Just noticed a bug whilst doing some test

- Preview a quiz
- Finish Previewing a quiz (all ok and user can still see preview/run quiz buttons)
- Refresh the page after 10 seconds and the preview/run buttons are gone. 😢

**Comment by sohilpandya** [comment]
@shouston3 You are correct, I can't seem to replicate this issue now on staging site either.. 😕 I was possibly having a long day brain melt... 😮 

Thanks for checking up on this, will close for now as its no longer an issue.

**Comment by stianr** [comment]
Problem still present when I tried it today.

**Comment by sohilpandya** [comment]
I've just tried to replicate this and am unable to replicate it locally. Tried both quiz and surveys 😟 

You can have a look at the movie attached below. 
![preview-quiz](https://cloud.githubusercontent.com/assets/2305591/24516946/52651002-1574-11e7-89d7-c07b5ddfc79d.gif)

**Comment by stianr** [comment]
Interesting. Looks like the problem only occurs if a student happens to be logged into the module when the quiz is being previewed. To replicate the issue:

- As a lecturer set up a new quiz with one question
- Using a different device or browser, log on to quodl as a student and then either join or navigate to the module containing the new quiz
- As a lecturer preview quiz ("Join Live Quiz" will illuminate for student, but can be ignored)
- After previewing quiz when you return to module overview page, manually refresh the page

The quiz will appear to have been run. If you can't replicate it let me know and I'll do a screen recording.

**Comment by stianr** [comment]
That would explain why the problem seemed to come and go during testing...

**Comment by stianr** [comment]
Seems to have solved it. I can no longer break it as I could before.
