### ISSUE TITLE
When there are less than 4 answers, students see blank squares in review

### ISSUE THREAD

**Issue by iteles** [cul-2016/quiz#443]
In this example there were only 2 possible multiple choice answers to this question, but options C and D still appear in the student question review section (as blanks).

![cul-app-bug-student2](https://cloud.githubusercontent.com/assets/4185328/22734510/d5ee5ca2-eded-11e6-9722-8414de032e47.jpg)

**Comment by sohilpandya** [comment]
This has been addressed and can be tested on staging.

**Comment by stianr** [comment]
Works for me.
