### ISSUE TITLE
Setting up Quodl on the live version of heroku

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#455]
Once #453 has been merged into the master, we need to go through the following steps to ensure that it is all working well.

- [x] run the latest build on the live app
- [x] update all the required env vars in live app. 
- [x] run the latest schema on live app
- [x] run through some tests to make sure all is ok on the live version.

**Comment by sohilpandya** [comment]
We've updated the live version of the app, refreshed the database with the schema and all is looking good on the live version of the app.

**Comment by stianr** [comment]
Great - so once the DNS updates have propagated, then presumably everything will work from quodl.co.uk?

**Comment by iteles** [comment]
Done! As per #374
