### ISSUE TITLE
Create an Amazon AWS account

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#456]
Hi @stianr, currently the sending of email is done via Amazon SES and is under my account, would it be possible for you to create an account for Amazon AWS so that we can replace them for the live version of the app. 

This isn't that high a priority and can be done when you've got a spare hour 😄 

Steps to follow: 
- Register for AWS
- create an IAM account 
  - select IAM
<img width="1834" alt="screen shot 2017-02-14 at 10 00 42" src="https://cloud.githubusercontent.com/assets/2305591/22924402/e10fb30c-f29c-11e6-81f7-4d96f599ce95.png">
  - select users from the side menu
<img width="1077" alt="screen shot 2017-02-14 at 10 00 55" src="https://cloud.githubusercontent.com/assets/2305591/22924425/f7dd14bc-f29c-11e6-877d-960a45995ea9.png">
  - create a new user
<img width="1864" alt="screen shot 2017-02-14 at 10 01 22" src="https://cloud.githubusercontent.com/assets/2305591/22924430/fa1da8b8-f29c-11e6-8247-6ae5a8b12f6c.png">
  - create a new group
<img width="1149" alt="screen shot 2017-02-14 at 10 01 44" src="https://cloud.githubusercontent.com/assets/2305591/22924436/00a72466-f29d-11e6-8301-692157a71194.png">
- Apply the SES full policy to the group which is applied to the new user. 
<img width="1780" alt="screen shot 2017-02-14 at 10 02 10" src="https://cloud.githubusercontent.com/assets/2305591/22924439/027baece-f29d-11e6-9a94-c866ebce7e3c.png">
- complete the steps and please keep hold of the ACCESS_KEY and SECRET_KEY (**Do not** put these on Github, Please send them over in a seperate email over to us)

- Once the setup for IAM role is completed go to SES from services
<img width="1529" alt="screen shot 2017-02-14 at 09 58 20" src="https://cloud.githubusercontent.com/assets/2305591/22924202/2bd65176-f29c-11e6-988f-8a4db0c9be83.png">
- Verify the email address you'd like to use for sending out the emails. 
<img width="1920" alt="screen shot 2017-02-14 at 10 08 21" src="https://cloud.githubusercontent.com/assets/2305591/22924598/a2f3ce0e-f29d-11e6-8e61-79275282e645.png">
- Moving out of AWS SES sandbox environment.
> When you first sign up to AWS, you are provided with a sandbox account. With this, you can
> send up to 200 emails a day, to email addresses that you have registered on your sandbox
> environment. For some use cases this is fine, but for those who want a higher daily sending
> quota, want to send emails without the restriction of registering recipient emails upfront,
> amongst other reasons 'moving out' of your sandbox might be beneficial. For many services,
> this upgrade comes with a cost, but with AWS SES, this is not necessarily the case. A quick and
> easy way to do so is to apply for an increase in your SES Sending Limit; (1) click on the following
> link, https://aws.amazon.com/ses/faqs/ (2) search for "apply" in section 4 and (3) click 'apply'.

Once you've been moved out of sandbox we can transfer the SES account details on Heroku. 

Please keep me updated, AWS process can be a bit lengthy at times.

**Comment by stianr** [comment]
Have done most of this, but I'm not getting the verification email, even after a couple of hours. I'll wait and see whether it comes through. If not, I'll try a different email.

**Comment by stianr** [comment]
It didn't seem to send out a verification email to no-reply@quodl.co.uk (though I've checked the email address is working). So I've used my City address for now. When applying to move out of Sandbox, there are questions about how it's going to be used. What answers should I give?

![image](https://cloud.githubusercontent.com/assets/16817089/23028116/49dfe0ce-f45e-11e6-9d07-fb9124fb9041.png)

**Comment by stianr** [comment]
@sohilpandya I didn't assign you so you probably didn't see this. I'm assuming I still need to finish this off?

**Comment by iteles** [comment]
@stianr Yes please! It would be good to transfer it to you. 
@shouston3 You recently filled one of these in too - could you give Stian some indication of what to include please?

**Comment by shouston3** [comment]
I would write the following for a [service limit increase](https://aws.amazon.com/ses/extendedaccessrequest/):
```
Region: EU (Ireland)
Limit: Desired Daily Sending quota
New Limit Value: 5000
Mail Type: System Notification
Website URL: https://www.quodl.co.uk/
My email-sending complies...: yes
I only send to recipients...: yes
I have a process to handle bounces...: yes
Use case description:
Amazon Ses is being used on our website to verify new users
and to allow users to change their password by sending them an email link
```

**Comment by sohilpandya** [comment]
Thanks for that @shouston3 ❤️

**Comment by stianr** [comment]
Yes, thanks @shouston3 - much appreciated. It did the trick, and I've been moved out of sandbox and had my sending limit increased. @sohilpandya, could you let me know what we need to do to effect the transfer?

**Comment by sohilpandya** [comment]
@stianr great to hear that we are out of the sandbox!

we will need to make a change to the Heroku vars which can be found under the settings.

![screen shot 2017-03-20 at 12 25 13](https://cloud.githubusercontent.com/assets/2305591/24099638/4bd1521e-0d68-11e7-9f37-f369239f8095.png)

We then need to replace the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY with your ones. Once that is done, you can test it out by trying one of the flows that require an email to be sent (e.g. forgotten password) 

If all goes well, you should receive the email and the transfer of AWS SES should be complete.

**Comment by stianr** [comment]
Thanks - using quodl in a large lecture in just over an hour, so will update after that, and report back.

**Comment by stianr** [comment]
Have updated AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY, but it now gets stuck whenever it attempts to send an email. I also tried updating AWS_REGION, as it was set to us-west (or at least something US-based), and my AWS approval is for EU (Ireland) - which looks like it should be eu-west-1. I've also tried setting up a second access key, and using those credentials. But again, no success. Any thoughts?

**Comment by sohilpandya** [comment]
Hi @stianr, 

It looks like the message from the log says that the email address that you are sending from is not verified.  `quiz.cityuni@gmail.com` 
![screen shot 2017-03-20 at 17 52 19](https://cloud.githubusercontent.com/assets/2305591/24113877/1cf6c270-0d96-11e7-9a1f-928ca2fb1902.png)

Could you please verfiy the email address and then try again.

**Comment by stianr** [comment]
Thanks - I don't own that email address, so I've updated with with hello@quodl.co.uk. It got confusing because my aws account was initially set up as US-based, so was only verifying for us-east-1 region rather than eu-west-1 as required. But all sorted now. Thanks for the help.
