### ISSUE TITLE
Register verification not working

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#458]
User has just tried to verify their email when registering as lecturer. Seems to be checking against staging version - says she's already registered but can't log in to non staging version as user is not verified. I have replicated issue. Please fix urgently.

**Comment by stianr** [comment]
Nb lecturer needs to set up quiz in next hour or so for running at 2pm.

**Comment by sohilpandya** [comment]
Hi @stianr, This issue has now been fixed, Any lecturer's that register from now on should have the correct URL that will take them to the live app. 

Please let me know the name of the user that has already registered, I can delete them manually and if they go through the registration process again, they should be able to verify.

**Comment by stianr** [comment]
Thanks for the quick fix! Please delete Amanda.burls.1@city.ac.uk and stian.reimers@city.ac.uk.

**Comment by stianr** [comment]
Lecturer has decided not to run it today so next run will be 10am tomorrow. Please can you advise whether it's safe for a (different) lecturer to register and set up quiz now for running tomorrow?

**Comment by sohilpandya** [comment]
Hi Stian, the lecturers can indeed start registering from now. It shouldn't be an issue. 

There are a couple of minor CSS issues still pending that are not merged into the master.
- navbar on lecturer registration screen
- CSS in the lecturer registration verification and confirmation pages. 

These changes shouldn't affect the functionality, only style related changes and I will update you once these are merged in as well. 

For now you can start registering lecturer without the above issue resurfacing.

**Comment by sohilpandya** [comment]
@stianr Please close if you're happy with the bug fix

Thanks

**Comment by stianr** [comment]
Thanks. (Have deleted the message with email addresses, as this is a public forum...)
