### ISSUE TITLE
Super admin dashboard: View/Delete students or lecturers

### ISSUE THREAD

**Issue by jackcarlisle** [cul-2016/quiz#465]
As a super user,
I should be able to view the super admin dashboard,
So that I can view or delete students or lecturers from the application

**Comment by stianr** [comment]
Deletion of a student or lecturer should do the following:

- Irreversibly anonymise the user's email address entry
- Replace nickname entry with a unique random name like "Anon2932" (nickname will still appear on leaderboard)
- Prevent that user from logging in (which the anonymisation should do)
- All other entries should remain unaltered

**Comment by stianr** [comment]
Superuser should be able to identify a particular user easily: Dashboard should present users in a logical order (e.g., alphabetical by email address), either separate tables for student and lecturer roles, or a field in the table indicate what role they have.
It would be helpful if it could also show the module associated with a particular student or lecturer, but this is not a requirement.

**Comment by stianr** [comment]
Have tested delete student - seems to work well. Student remains logged in and can continue participating until they log out, but after that cannot participate. Leaderboard is updated, and csv downloads also.

**Comment by stianr** [comment]
And have tested for lecturer, checking for no impact on student viewing scores. All seems to work as it should.
