### ISSUE TITLE
Super admin dashboard: Download CSV

### ISSUE THREAD

**Issue by jackcarlisle** [cul-2016/quiz#466]
As a super admin user,
I want the ability to download CSV data for full answer datasets and full quiz question sets,
So that I can process and review it.

**Comment by stianr** [comment]
The precise dataset retrieved can be a bit flexible depending on the structure of the underlying databases, but it should be possible to download all data.

If using a set of relational databases, it would be fine to have separate options for dumping the contents of each database (I don't know the structure, but, e.g., Users, User-Questions, Question-Answers etc.). That might be most useful.

Alternatively, if easier, collate, and allow download of the following as a minimum:

1. Csv of full answer dataset with one participant-question combination per row, and columns of lecturer email associated with quiz, 4-letter module code, student nickname, student email, quiz number, question number, option chosen (A, B...), correct (1, 0, blank [for surveys]), timestamp for when entry made (if recorded).
2. Csv of full quiz question set, with one question per row and columns of lecturer email associated with quiz, 4-letter module code, quiz number, quiz name, question number, question wording, Option A wording, Option B wording, Option C wording (or blank) … Option G wording (or blank), correct answer (A-G or blank for survey), timestamp for creation, timestamp for run.

**Comment by sohilpandya** [comment]
Hey @stianr we wanted some clarification on the dataset that you required. Could you please have a look at the table below and let us know if our thinking is correct for what you are after. 

| lecturer email | module code | student nickname | student email | quiz_id | question_id | option chosen | correct option |
| ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- |
| lecturer@city.ac.uk | TEST | student | student@city.ac.uk | 1 | 1 | A | A |
| lecturer@city.ac.uk | TEST | student | student@city.ac.uk | 1 | 2 | A | A |
| lecturer@city.ac.uk | TEST | student | student@city.ac.uk | 1 | 3 | A | A |
| lecturer@city.ac.uk | TEST | sohil | sohil@city.ac.uk | 1 | 1 | B | A |
| lecturer@city.ac.uk | TEST | sohil | sohil@city.ac.uk | 1 | 2 | C | A |
| lecturer@city.ac.uk | TEST | sohil | sohil@city.ac.uk | 1 | 3 | A | A |

**Comment by sohilpandya** [comment]
## **2**
| lecturer email | module code | quiz_id | quiz_name | question_id | question_wording | A | B | C | D | correct_answer |
| ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- |
| lecturer@city.ac.uk | TEST | 1 | Test Quiz Name | 1 | What is the capital of England | London | Manchester | Cardiff | Brighton | A |
| lecturer@city.ac.uk | TEST | 1 | Test Quiz Name | 2 | What is the capital of Wales | London | Manchester | Cardiff | Brighton | C |

**Comment by stianr** [comment]
Yes, that looks great. 

For 2, is it possible to have an 'is_run' column which shows whether the quiz has been run yet? (Minor thing, so leave it if would take more than half an hour to add.)

If there's a way of getting a timestamp column in one of the datasets (so I could, for example, write some code to check what quizzes have been run / how many responses have been received this week/month/today) that would be even better. But if none of the databases contain time information at the moment, we can park this for now - I can always take regular downloads and compare.

**Comment by sohilpandya** [comment]
Yes, Stian we'll look into adding the is_run column for the 2nd one. 

unfortunately, we are not storing time stamps for Quizzes and that would involve a significant overhaul and would require some time to build in.

**Comment by stianr** [comment]
This looks good. At the moment the download does not include surveys I don't think. If we could include them as well (but have correct answer as a dash) that would be more complete.

**Comment by iteles** [comment]
@stianr Thanks for testing this.

When this issue was originally estimated, we had assumed from the conversations had and the comments above that this was required only for quizzes and not surveys. Without a doubt, this feature would be more complete with them.

Adding surveys will take an additional 2 hours of time. 
We will be checking on our standup in the morning, but at the moment, it looks like this can still be fit into the current sprint ending tomorrow!

However, from your comment above, the priority for this issue isn't 100% clear, so in order to confirm we are spending those 2 hours where they would create the most value to you, could I ask that you please:
+ Open the issue for surveys as a separate (closing this one)
+ Assign a priority to it, in relation to the other issues in the backlog - feel free to drop it into the Sprint 6 milestone if you'd like us to work on it tomorrow.

**Comment by jackcarlisle** [comment]
## **2 UPDATE**
| lecturer email | module code | survey_id| quiz_id | quiz_name | question_id | question_wording | A | B | C | D | correct_answer |
| ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- |
| lecturer@city.ac.uk | TEST | 1 |  - | Test Quiz Name | 1 | What is the capital of England | London | Manchester | Cardiff | Brighton | A |
| lecturer@city.ac.uk | TEST | 1 |  - | Test Quiz Name | 2 | What is the capital of Wales | London | Manchester | Cardiff | Brighton | C |
