### ISSUE TITLE
Viewing an individual Module

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#47]
#5 

**Client Side**
- [x] component to view a module
- [x] container
- [x] actions/reducers 
- [x] react router setup for viewing module  

**Server Side**
- [x] Endpoint to fetch data when viewing a module
- [x] DB call to fetch all the related information 
    - [x] Module Details - Module Table ( name ) 
    - [x] Medal and Trophy Details
    - [x] No. of users for the given Module - module_members Table ( count Unique user ID. )
    - [x] List of all quizzes for the given Module (including number of question for each quiz) - Quizzes Table ( quiz, number of questions, isPresented )
    - [x] No. of users who have completed the quiz - Response Table ( count Unique user ID that have competed each given quiz )

**Comment by minaorangina** [comment]
#### DB queries to keep in mind
* Get quiz and number of questions (count number of questions where quizID = n)
* Count number of entries per quiz (count unique userID where quizID = n)

**Comment by minaorangina** [comment]
#### Things to consider

* When adding a new quiz, how to we keep hold of the primary key (quiz_id) to then insert into the questions table?

**Comment by sohilpandya** [comment]
This is how you would return a value after inserting into the table. http://stackoverflow.com/questions/2944297/postgresql-function-for-last-inserted-id

**Comment by minaorangina** [comment]
### Distinct
Let's say we want a list of students who have taken part in a quiz
```
SELECT DISTINCT(user_id) FROM responses WHERE quiz_id = $1
```

**Comment by minaorangina** [comment]
### Count
If you need to count rows, you can do it like this:
```
SELECT COUNT(user_id) FROM responses WHERE quiz_id = $1;
```

**Comment by minaorangina** [comment]
### For each of this category, do some maths
```
SELECT arbitrary_category, SUM(my_column) FROM table GROUP BY arbitrary_category
```
```
SELECT arbitrary_category, COUNT(my_column) FROM table GROUP BY arbitrary_category
```
