### ISSUE TITLE
Housekeeping: Cookie Warning and Privacy Statement 

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#470]
As a student or lecturer using the system, I want to be warned that a cookie is being set on my device before it is set, and have the option to find out about what cookies are being used for. I also want to be able to view a privacy statement to tell me how my data will be used, and how to have my data deleted.

- [x] Create a static webpage to hold the privacy statement (I will provide appropriate text)

- [x] On the create account page (https://www.quodl.co.uk/#/register-student), immediately above the 'Register' button, include a checkbox (easily checkable on a mobile device or tablet) along with the text "I agree with the [privacy statement](/privacy.html), including the [use of cookies](/privacy.html#cookies)." 

- [x] On clicking either of the links, create either an in-window pop-up or new window displaying either the privacy information, scrolling to the cookies section where necessary.

- [x] On clicking 'Register', check the status of the consent checkbox. If it is selected, continue as currently. If it is not, give an alert where the user sees a message along the lines of "Tap the box to agree and proceed", and remain on current page.

- [x] On the lecturer and student dashboard page ([https://www.quodl.co.uk/#/dashboard](https://www.quodl.co.uk/#/dashboard)), below any modules that have been added, include a small piece of text "View [privacy statement](/privacy.html)", which as above either creates an in-window pop-up or a new window with the privacy text in.

**Comment by jackcarlisle** [comment]
Hey @stianr could you forward us the copy for the privacy and cookie terms and conditions please?

**Comment by stianr** [comment]
Will work on this shortly. For now, could you use lorem ipsum filler text?

**Comment by sohilpandya** [comment]
Yes, we’ve got some Dummy text in there for now. Will change when we receive the statement. 

Thanks @stianr

**Comment by stianr** [comment]
Looks great - thanks Sohil! Have just sent over some text for the privacy/cookies statement.

One thing to look at is the validation of checkbox. At the moment, the 'Register' button doesn't illuminate until the box is checked. I think this will be a stumbling block for students, who don't get any guidance on why they can't progress. I had a call from a lecturer last term who was trying to set up a quiz and was pulling her hair out because the 'Save and Exit' button wasn't clickable. It turned out she hadn't specified the correct answer for one of her questions, but without any indication of what was wrong, she just got stuck and assumed there was a bug in the app.

So it would be ideal if we could go for the flow in the fourth bullet above - the 'Register' button illuminates whatever the status of the checkbox (if everything else is completed) but if clicked without checkbox being selected, it highlights the checkbox and explains it needs to be checked.

**Comment by stianr** [comment]
Looks great - validation works nicely.
