### ISSUE TITLE
Swapping question order

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#471]
As a lecturer I want to be able to reorder my questions  when setting up (/new-quiz) or editing (/edit-quiz) a quiz.

At the moment, questions are presented vertically, and lecturers can add questions at the bottom of the question list, but can't reorder questions. 

Ideal solution would be for lecturers to be able to drag and drop a particular question to insert it elsewhere in the quiz. So if lecturer dragged Question 6 up and released it between Question 3 and Question 4, the current Questions 4 and 5 would become Questions 5 and 6, and the released Question would become Question 4. (A bit like [https://jqueryui.com/sortable/](https://jqueryui.com/sortable/)).

A less elegant solution (but may be better if the drag-and-drop option is likely to be very time consuming), would be for each question to have an up and down arrow on it. Clicking on one of the arrows swaps the question with the one directly above or below it, if one exists.

**Comment by sohilpandya** [comment]
Thanks for the detailed issue, we'll try to implement the drag and drop option for this. 

Here are some of the options available:
- Drag & Drop using - https://react-dnd.github.io/react-dnd/ 
- Drag & Drop using - https://github.com/clauderic/react-sortable-hoc
- Drag & Drop using - https://github.com/JakeSidSmith/react-reorder

We'll be running a small spike with a couple of the modules to find out which one is the best to proceed with.

**Comment by jackcarlisle** [comment]
NOTE: **This also needs to be implemented for surveys**

**Comment by stianr** [comment]
This is a work of beauty - fantastic! 

I have tested it on Chrome, Firefox and IE11, with different numbers of options and surveys as well as quizzes, and it seems to work as it should in all cases.
