### ISSUE TITLE
Restoring Trophies

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#472]
The prototype version (Oct 2016) of the app had both medals (for performance on a quiz), and trophies (for achieving certain goals. This functionality was removed in the latest version because it contained bugs and the styling of leaderboard and end of quiz pages had omitted the use of trophies. Some background to trophies is in these issues: #97, #117, #398, #399.

To restore the trophy functionality I think we need to do the following:

- [x] Reinstate the trophy options for lecturers when adding a new module (https://www.quodl.co.uk/#/add-new-module). I think these were originally implemented and then hidden, so it should be fairly straightforward.

- [x] For students, display individual trophies on the module overview page (https://www.quodl.co.uk/#/XXXX/student). This is something for the designer to look at, but for development, it needs to be possible to check the status of each of the four potential trophies, and show them as either awarded or not.

- [x] On the end-of-quiz page, display an trophies that have been awarded. Again, we should get input from the designer for this, but the end of quiz procedure should check whether any new trophies have been awarded, as we had with the prototype

- [x] On the leaderboard, as well as showing the medals, add columns for each of the four trophies, so for each student the trophies are displayed as either awarded or not (see #217 for a screenshot of the prototype that includes trophies).

We have the complication of the 'Last Quiz' checkbox when setting up quizzes. This was added so that overall performance could be calculated, and students scoring above a certain percentage would get a particular trophy at the end of the last quiz. It might be worth discussing this - I think there are two options 

- Restore 'Last Quiz' functionality and trophies as before.

- Change the criteria for awarding trophies to be based on absolute rather than percentage criteria (so when setting the module up, the lecturer gives the number of correct answers that are needed for a trophy rather than the percentage at the end of the quiz series. This might be easier).

**Comment by jackcarlisle** [comment]
Hey @stianr we're just reviewing this issue for the trophy feature. After an initial look we feel as though rewarding trophies based on absolute values will be a more maintainable solution.

It will be one that we will be able to implement relatively quickly compared to the trophies for percentage values which has been implemented before and was found to be buggy. 

Please let us know if you're happy for us to make the following changes:

| Previous Trophy | Proposed Trophy |
| --------------- | ---------------|
| overall_average (%) | overall_score (Integer) |

Thanks!

**Comment by stianr** [comment]
Yes, that works for me. So I'm assuming we therefore won't need the 'last quiz' button or any of that stuff.

**Comment by sohilpandya** [comment]
Nope. We’ll have to take that out and create a new query for the change above but It should be straight forward.

**Comment by stianr** [comment]
That makes a lot of sense - I think it made things a lot more complicated for very little gain...

**Comment by sohilpandya** [comment]
That would be possible, but we'll need to look at that separately once we implement the restoration of trophies as It will have impact across the app and not something we just want to attach to this issue.

**Comment by stianr** [comment]
Sure - can see it could have substantial knock-on effects. I was just posting it here, and now, in case it affects how you'd tackle restoring the trophies.

**Comment by jackcarlisle** [comment]
### -Technical comment-

In order to determine whether or not a student has received a trophy at the moment of completing the quiz, we will need to compare it against the trophies that they have before taking the quiz. We will need to set the state of the trophies when the application loads for the first time and then compare the differences after each completed quiz

**Comment by sohilpandya** [comment]
Hi @stianr can you please test this feature, we've implemented it back into the staging branch. 

Please note that the quiz result page for students and leaderboard are not styled, so at this point you will only see the trophies in text form. Once we've finalised the new designs we will be implementing those.

**Comment by stianr** [comment]
All looking great, and functionality seems right in my testing. Will continue to test and will reopen if any issues arise.
