### ISSUE TITLE
Update dependecies. 

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#480]
@jackcarlisle we’ve already done this but for some reason the icons on the reader are still showing out of date dependencies. We need to see what’s causing this. 😊

**Comment by sohilpandya** [comment]
We'll update the out of date dependencies one by one. 

nb. we will not update the dependecies if they break the code. for e.g. react router from 3 -> 4 will break so we will not update it.

**Comment by iteles** [comment]
👍 This was done throughout.
