### ISSUE TITLE
Deployment of features to staging for PO testing

### ISSUE THREAD

**Issue by iteles** [cul-2016/quiz#486]
As a member of the dev team, 
I would like to deploy features to our staging site (https://cul-app-staging.herokuapp.com/) _as_ they are completed during the course of the sprint
So that our Product Owner can review these and comment on them, allowing the team to catch any issues early.

**Comment by sohilpandya** [comment]
Hi Stian, we've updated the staging version of the app and would like you to test out all the issues that have a `please-test` label on them. https://github.com/cul-2016/quiz/milestone/10

It would be great if you were able to test out these and provide us feedback on them. Please log in as a lecturer using the `lecturer@city.ac.uk` as that is the only user who has access to the super admin area. 

If you would like us to add the super admin role to your account, please provide us with the email address that you've registered with and we can update it in the database. 

Thanks.

**Comment by stianr** [comment]
Brilliant. Thanks. Please could you add super admin access to the stian.reimers@city.ac.uk account - I'll be able to access it from there.

**Comment by sohilpandya** [comment]
@stianr this is the staging version of the app and not the live version, the data gets cleared on this app at a regular interval as we implement features/update it. We'll email you the account details for the dummy lecturer which will give you access to the super admin. 

We will only deploy this to the Live version after the demo on Monday.

**Comment by iteles** [comment]
@stianr Just a couple of process points on this, I see you've already begun testing everything this afternoon which is excellent 😊 

+ If an issue has been completed successfully (e.g. https://github.com/cul-2016/quiz/issues/471#issuecomment-323118211), please **close the issue** to denote this
+ If an issue has not been completed or there is an open questions on it (e.g. https://github.com/cul-2016/quiz/issues/470#issuecomment-323076480) please assign it back to @sohilpandya and @jackcarlisle and remove the `please-test` label 

That would be wonderful!

We'll be aiming to push to staging more often throughout the coming sprint, so you should see more of the `please-test` labels popping up. We'll discuss it at our sprint planning on Monday!

**Comment by iteles** [comment]
Excellent, thanks @stianr !

Closing this issue as it's now complete.
