### ISSUE TITLE
CSS update for adding modules for a students

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#491]
Currently there is a minor bug in the CSS when a user is on smaller phone sizes (e.g. iPhone 5) where the `add module` section doesn't stack up.

**iPhone 5**
![screen shot 2017-08-17 at 15 34 24](https://user-images.githubusercontent.com/2305591/29417633-c7255ffe-8361-11e7-96af-47f27d0c9636.png)

**Need to fix it so that it looks like this on iPhone 5:**
![screen shot 2017-08-17 at 15 34 36](https://user-images.githubusercontent.com/2305591/29417653-da108b84-8361-11e7-8be8-a501214adb47.png)

**And like this on iPhone 6 onwards:**

![screen shot 2017-08-17 at 15 34 43](https://user-images.githubusercontent.com/2305591/29417649-d7c0d6d6-8361-11e7-9b3d-6ef960157ac1.png)

**Comment by stianr** [comment]
Maybe something to look at with the designers, but would be ideal if on most phones the full four letters displayed at the same time. On Samsung Galaxy S7, only three are shown. Best solution might be to make field wider and button narrower and change text to "Add Module". But can discuss.

![image](https://user-images.githubusercontent.com/16817089/29420853-2aca5060-836b-11e7-91bc-a7607a854c94.png)

**Comment by sohilpandya** [comment]
@stianr could you please test this on the s7 again, the change made in pr #492 should have fixed the issue.

**Comment by stianr** [comment]
Is it live on the staging version? Nothing seems to have changed on S7 Firefox or Samsung browser.

**Comment by sohilpandya** [comment]
@stianr could you please test it now, I've updated the staging version again.

**Comment by stianr** [comment]
Alas it still looks as it does in the screenshot above, on both browsers.

**Comment by stianr** [comment]
Now fixed - looks good!

![image](https://user-images.githubusercontent.com/16817089/29466349-7b6a8a16-8434-11e7-8e3b-ad3e7000c4af.png)
