### ISSUE TITLE
Keeping positioning constant with button presses

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#496]
For most of the buttons within Quodl, when they are pressed (i.e., mouse down but not released), their styling changes (which is good), but the position of other elements, generally below them, on the page jumps slightly (which is less good). This can be seen to varying degrees on the 'View Leaderboard' , 'n Students' and 'Add A New Survey/Quiz' buttons on the lecturer module overview page, and the 'Survey' 'Add Question' and 'Delete Question' buttons on the add quiz page, and probably elsewhere.

It would be a slicker experience for the user if pressing a button did not change the position of anything else on the page.

**Comment by sohilpandya** [comment]
@stianr can you please test this as it has been resolved on the staging version of the app.

**Comment by stianr** [comment]
Looks fixed to me.
