### ISSUE TITLE
Sprint 6 demo flow

### ISSUE THREAD

**Issue by iteles** [cul-2016/quiz#499]
+ Create an account to show #470 Cookie warning & privacy statement
  + Show privacy policy statement
  + Show error message if the person doesn't agree
  + Create new quiz
    + Swapping question order #471 
    + Show preview of quiz (now doesn't set quiz to run) https://github.com/cul-2016/quiz/issues/439
+ Log out and log in as super admin
  + Delete/add users #464 
  + Download data for quizzes & surveys #493 
  + Down load CSV #466 
+ CSS update for adding modules as student https://github.com/cul-2016/quiz/issues/491
+ FF bug https://github.com/cul-2016/quiz/issues/196

**Comment by sohilpandya** [comment]
Worked well. closing this issue now. :)
