### ISSUE TITLE
Redesign of the App

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#518]
Hi @stianr,

We're coming up to the end of the list of Priority 3 features and wanted to write down the list of items that need to be completed in terms of the design and potential time estimates. 

Fortunately, @harrygfox & @nogainbar have implemented some of the redesigns throughout the lecturer's side of things, this gives us a perspective into the designs and styles that will be used throughout the app. Certainly a lot more consistent throughout the site. 

Our time will be split up into these major items:
- Apply the redesign to the rest of the lecturer and Student views. 
    - Module overview 
    - Live Quiz 
    - Leaderboard
    - All of the student screens for mobile
- Update the student module screen with the updated trophy designs
- Update the student quiz result screen with the updated design and potential animations

We'll also need to spend some time making sure all of the functionality is working as expected after some major changes that will be taking place. 

We are expecting the spend the rest of the time after the long weekend on styling and polishing as we hope to finish the p-3 features by the end of today, but we just wanted to make you aware that we may not get through all of the screens by the end of the sprint, this doesn't mean that we will not provide designs for some of the screens only that some screens may not look pixel perfect by the end of the sprint due to the short time available. 

Please let us know your thoughts and we hope to hear back from you.

**Comment by stianr** [comment]
Thanks for the update @sohilpandya. So just to clarify in my head what's likely to be achieved by the end of Sprint 7, it looks like we'll have:
- Trophies restored to how they were in prototype #472 
- Ability to share quizzes #484 
- Students have option of reviewing quiz without correct answer revealed #473 
- Showing loading icon #495 
- Bugfixes #515 #496 
- New styling of most of the pages

Things that won't be implemented:
- Increasing the number of options beyond 4 #485 
- Allowing lecturer to add information about the correct answer to help with student revision #485 
- Making quiz full screen #357 
- Possibly some of the styling of some pages

If that's the case then yes I agree that focusing on the styling - particularly for the most used pages (so the members pages and quiz review page for lecturers would be lower priority than the module overview and run quiz pages - which I'm sure you're already prioritising). 

By the end of the sprint it would also be useful to have time estimates for all of the non-implemented stuff - we have it for most, but I think need if for the two elements of #485. 

Hope the final week goes well!

**Comment by iteles** [comment]
Any remaining items here captured in #551, closing this issue for now 👍
