### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#53]
- [ ] React Motion 
- [ ] Velocity React (created by Twitter)
- [ ] React Addons CSS Transition Group
- [ ] Simple CSS Animations No React

Idea is to look into the best way to create animations for the application. From Medal/Trophy awards to moving onto the next question.

**Comment by sohilpandya** [comment]
https://react.rocks/?q=animation

**Comment by sohilpandya** [comment]
**ReactCSSTransitionGroup**
Simple Animation using CSS transitions. I will try to implement this in the adding of questions section and post the results below.

**Comment by minaorangina** [comment]
[React Motion docs](https://github.com/chenglou/react-motion)

**Comment by minaorangina** [comment]
[CSS Animation generator](https://coveloping.com/tools/css-animation-generator)
