### ISSUE TITLE
Remaining Styling Implementations

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#536]
**Lecturer**

- [x]  Back Button in nav bar needs stying (padding)
- [x]  New Module badge needs to be replaced with the new one.
- [x]  New Module Gold Line needs to be changed to Grey one.
- [x]  View Leaderboard Quit button in nav bar needs to be implemented.
- [x]  LeaderBoard Badges need to be implemented
- [x]  @harrygfox @nogainbar What is the diff? What would you like to happen there?
- [x]  View Students change card css and button css
- [x] Add a new quiz/survey update input styling and colour of toggle to new blue
- [x]  Quiz Details Button Colours need to be adjusted as well as the card
- [x]  Quiz review colour of right answet needs to be changed from gold to blue.
- [x] Live-quiz waiting page text/buttons need to be updated.

**Students**

- [x] MY Performance page needs style changes
- [x] @jackcarlisle is nearly done with the student module dashboard
- [x] Review & Revise pages need style changes to conform to the new designs
- [x] Live Quiz page minor changes need to happen.
- [x] Finally the main piece of the puzzle is the results page. This is what @nogainbar & I spent a couple of hours on. We managed to get greensock working. so My plan for today is to firsly get that page looking nice and as expected, then add the Animations. I am hoping to be very close/done by the end of day today. Which will leave us with all of the minor changes that need to happen from the list above.

**Comment by harrygfox** [comment]
For the following:
![image](https://user-images.githubusercontent.com/7805691/29977440-413fcc14-8f35-11e7-8c7b-e06bc96af432.png)
fyi There is a new navbar structure that uses the navbar--invisible modifier and a navbar__item--onlyone modifier which creates plenty of space around the single link to click on

**Comment by iteles** [comment]
:+1: Closing this as #519 is where @stianr will be testing this and this issue was an internal checklist.
