### ISSUE TITLE
Functionality bugs/enhancements

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#544]
To do before deployment
- Reviewing answers presents the questions in the opposite order to that used in the quiz presentation (last question at top of page). We should use same order - some questions might refer back to earlier ones (e.g. Q1 “What’s the best treatment for a migrane?” Q2 “Why is that the best treatment?” – confusing if presented in the opposite order…). This occurs for (a) Student view "my answers", (b) student view “revise”, (c) lecturer view “review quiz” (for presenting to students), (d) lecturer "quiz-review". 
- Deleting options when setting up or editing a quiz doesn’t delete the option when presenting quiz. To replicate the issue, as a lecturer add a quiz, and add a single question. Type some text into each of options A, B and C, then delete the text from C and indicate the correct answer A or B. When running the quiz, Option C appears as an empty box (also appear on student view and on revise/my answers. 
- When running quiz as lecturer, ‘Next question’ button should have a 1-second delay before it becomes clickable – it’s very easy to double click and so skip over the next question (I’ve accidentally done it a couple of times), which would be very bad in a lecture. 
- Entering an invalid module code as a student in Add a Module give ‘Whoops! something went wrong in…’ text at bottom of the screen. Error should be caught and display ‘Code not found’ text to user. Currently doesn’t seem to cause problems though - so maybe okay just to suppress error message?

**Comment by iteles** [comment]
Thanks for these @stianr. I suggest we move the 'for future work' section into separate issues that can be kept in the backlog for future prioritisation and estimation.

@sohilpandya As discussed earlier today, are you able to please estimate the 'To do before deployment' section of this issue?

**Comment by sohilpandya** [comment]
Hi @stianr, I've added my time estimates for all of the points above. My first preference is to display an error message to the students but if I am running out of time, I may just suppress the error message. Not first choice though.

**Comment by stianr** [comment]
Thanks @sohilpandya - those time estimates look fine, so please do make these changes.

**Comment by stianr** [comment]
Thanks @sohilpandya Question order fixed. Delay is great. Invalid module error is captured.

The deleting options fix works for the quiz presentation, but the empty options appear in the lecturer quiz review (at least the time I tried it). Is it possible to suppress them there too?

**Comment by stianr** [comment]
By 'lecturer quiz review' I mean the running through the questions immediately after the quiz, not the review that the lecturer can come back to by clicking on 'details' on a run quiz.

**Comment by sohilpandya** [comment]
Hi Stian, just pushing this to staging as well, the above should now be fixed.

**Comment by stianr** [comment]
@sohilpandya looks fixed to me - thanks!
