### ISSUE TITLE
Styling issues/enhancements

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#545]
Testing #519 

To do before deployment

- Student styling for non-mobile devices: Currently two badges stretch to fit the full width of the screen no matter what width it is. For a desktop or tablet in landscape mode, this is massive, and means a lot of scrolling to get past the badges. Even on a mobile in vertical orientation they take up most of the screen so students may miss the information and feedback below. Can we (a) have all four badges on a single line unless the screen width would make them impossible to see properly (on a typical smartphone I think they’d be fine on one line), and (b) have the maximum width of the element containing them at around 800-1000px (or whatever you find works best…) so that they don’t become massive relative to the text on the page when viewing on a laptop or horizontal tablet. 
- Lecturer/student sign-up text "Please agree to the privacy statement before proceeding" is almost unreadable (Desktop/Chrome). Maybe use same styling as “Invalid Email Address” for login page – plain red text.
- The trophy thresholds need units: "Total score across all quizzes", "Percent correct on any one quiz", "Number of quizzes taken". The numbers don't make a lot of sense to a new user currently. (More general thing where we could add more '?' icons to give further information.)

**Comment by iteles** [comment]
Thanks for these @stianr. I suggest we move the 'for future work' section into separate issues that can be kept in the backlog for future prioritisation and estimation.

@sohilpandya As discussed earlier today, are you able to please estimate the 'To do before deployment' section of this issue?

**Comment by stianr** [comment]
Makes sense - I've just dumped them into a single separate issue now. @sohilpandya, it might be worth still having a look at those in case there's anything that would be very easy to do now while you're working on the current fixes, but harder later. I thought the maximum width formatting for the badges for laptop/tablet student view might be easy to apply to all pages, which would also solve one of the issues for future work. But it might not be easy of course...

**Comment by sohilpandya** [comment]
Hi @stianr, I've attached the time estimate for all three items in this issue. For the last point 
>The trophy thresholds need units: "Total score across all quizzes", "Percent correct on any one quiz", "Number of quizzes taken". The numbers don't make a lot of sense to a new user currently. (More general thing where we could add more '?' icons to give further information.)

I'll be adding the units and not going down the route of a `?` which would require more time and some potential design input with regards to where it would go. Is it ok to proceed with units inline?

**Comment by stianr** [comment]
Hi @sohilpandya - that makes sense re the '?', something that could be implemented more widely in future work. Please do go ahead and make the other changes.

**Comment by stianr** [comment]
I'm not seeing these changes in the current version on heruko.

**Comment by sohilpandya** [comment]
Apologies, Stian, Looks like the auto-deployment failed yesterday. I've updated the staging version now and the changes should be reflected on the app.

**Comment by stianr** [comment]
Thanks @sohilpandya. This is all looking good. The only thing that hasn't been implemented is putting all the badges on a single line (point a in the first bullet). That would be neater when viewed on a monitor, and would mean that the badges didn't take up the whole screen on mobile. Would that take a lot of time to do?

**Comment by sohilpandya** [comment]
Hi @stianr, this has also been pushed up onto staging, could you please view the student dashboard on a larger viewport and please let me know if it looks ok. 

Thanks!

**Comment by stianr** [comment]
That's fixed when viewing on a monitor. On a Galaxy S7 the badges are still on two lines, but given time constraints let's leave that for future work.
