### ISSUE TITLE
Styling and functionality updates for future work

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#546]
Styling

- Question element in add/edit quiz has more padding than it needs – hard to change order when only able to fit 1-2 questions on a screen (Desktop/Chrome/HD resolution). Remove some of the padding, default each option text field to being one row high (plus padding so it doesn’t look too cramped. Fantastic decision to make the text fields resizable – if lecturers want longer answers, they can drag. Would suggest making text fields only user-resizable vertically – at the moment users can also move it horizontally, which looks a bit odd and misaligns the ‘correct’ toggle. Constrain minimum height of text field to be one line, and maximum three lines.
- Clicking on a badge in the student module overview page enlarges the badge (to show off the artwork!), and shows criteria for being awarded it.
- Student quiz review “My answers” and “Revise” stretches to full width of screen on desktop/laptop/tablet. Would be better to have a maximum width as with other elements so it’s easier to read.
- Styling for question presentation on mobile could be improved – should be possible to present a standard length question and four options on a mobile screen without scrolling. E.g., move question number to top left corner and have text to right. Reduce padding for each option, and between options.
- New module page styling - could be restyled a little, to make medals and badges take the same amount of the screen. 
- In add/edit quiz, standardise text entry fonts across quiz name and question/option wording.
- Privacy statement on mobile needs more padding – bullet points are partially off the screen

Functionality 

- Save-and-exit button on add/edit quiz should give an alert when pressed as to why the user cannot proceed (as with the registration page) –saying something like “Please ensure that all questions have at least two options, and you have you have indicated the correct answer for all questions.”
- Joining the quiz increased the number of students on the lecturer waiting page by 2. But then got to the right number in the end somehow.
- After submitting to register as lecturer, https://cul-app-staging.herokuapp.com/#/please-verify  gets stuck on a 'Loading' screen. (No need to fix now - functionality is fine, verification email gets sent, and verification works. I'll be setting up lecturer accounts for this term's test, so no-one else will see it.)
- Blank leaderboard should have “--- No scores yet ---” or similar to show that it’s not failing to retrieve scores.

**Comment by sohilpandya** [comment]
Hi @stianr, here are my estimates for the above:
**Design**
T4h
**Functionality**
T4h, unable to put an exact number for the number of students increased by two, so I'd suggest a spike and then get back to you with a better estimate on that point. Total would be T4.5h including the spike

**Comment by stianr** [comment]
- Put all badges on a single line when viewed on common smartphones so that they don't take up the whole page. See #545 for background.

**Comment by stianr** [comment]
Hi @jessicasalmon!

> We can enlarge it, but we are currently not storing the relevant information so to do this we'd need to make a fetch request to get this information. This will take slightly longer than expected, so please let us know your thoughts on this.

I think this is worth doing if it's just a couple of hours extra, say. It's more important than enlarging it, as it helps students work out what they need to do to receive the badge.

> Could you clarify what you mean here please? We took a look but the fonts are looking the same to us, a screenshot would really help us to see it.

See below - the quiz name 'Short but wordy' and question text entry ('lorem ipsum...') fields use different fonts. On Chome/Win7 anyway...

![image](https://user-images.githubusercontent.com/16817089/35235113-2077d194-ff9b-11e7-9a99-3a50cff9befc.png)

**Comment by sohilpandya** [comment]
Thanks for that Stian, I've also updated the labels on this issue to refer to the correct time estimations as seen in the original comment above https://github.com/cul-2016/quiz/issues/546#issuecomment-329616797

**Comment by sohilpandya** [comment]
Hi @stianr, the items are ready for you to test on staging version of the app. cul-app-staging.herokuapp.com

Styling:
- Given the question input area minimum height of 1 line and max of 3 lines, also made the width fixed so users can only resize horizontally. We've looked at reducing the padding between questions and we need more time as it will need to be rethought due to the height of the correct answer toggle. Hopefully, this can be done later
- We are showing the criteria for each badge on student module, As discussed, we're displaying the criteria at all time instead of clicking the badge as it is not intuitive that the badges can be clicked on mobile. I'll also attach the screenshot of how it looks when they are all in one row.
- Revise and my answers have a max-width
- Live Quiz view on mobile has been improved, now fits 4 answers on the screen.
- New Module page, we've made the medals and trophies similar in size. 
- Add/Edit quiz we've standardised text entry font.
- Privacy statement added padding. 

Functionality
- Save and Exit button now gives an alert
- Fixed loading screen issue on register-lecturer
- Blank leaderboard now has the text "No scores Yet"

- We have looked into the issue related to the number of students increasing by 2. The issue seems to be related to the number of tabs the student has open, we were able to replicate it by having multiple tabs open for the same user which led to count increasing by two. 

_trophies on one row_
![screen shot 2018-01-23 at 17 16 09](https://user-images.githubusercontent.com/2305591/35327930-c75a015a-00f2-11e8-9cbd-8becea9c808e.png)

**Comment by stianr** [comment]
Hi @sohilpandya @jessicasalmon, thanks for this.

I agree re the badge positions/sizes - sensible decision to leave as it is.

The update on the criteria for badges on the student view wasn't quite what I was looking for (I think we discussed it but it's not in the text of the issue, so I can see why things were done as they were). The idea is that the user sees not just the criteria but their progress towards it (e.g., 3/5 quizzes completed; 23/35 correct answers). If the student can see the criterion but not where they are relative to the criterion it won't help them as much. What you've done is definitely an improvement, but if time allows showing the student's own score would be really helpful.

**Comment by stianr** [comment]
The consistent font and single line option entry are good (though I was only recommending having a single line to make it more compact, which it hasn't done).

I think the field height for options needs to be larger to accommodate the font size as I get little arrows in the top right of my fields which disappear when I increase the height (see below):

![image](https://user-images.githubusercontent.com/16817089/35332188-002458d2-0102-11e8-83b6-14a27c21a7ef.png)

As you say, the overall space taken by the question hasn't changed, but maybe we can look at that when you add the extra field to let lecturers include information about the right answer. That will involve some working with the styling already, so that might be the time to work on removing the padding elsewhere.

**Comment by stianr** [comment]
The error message is nice - wondered if it would be possible to be specific about what the unmet criterion for acceptance is:

- Please ensure that all questions have at least two optiona
- Please ensure that you have indicated the correct answer for each question

At the moment if I go to set up a survey rather than a quiz, it gives the same generic error message telling me I need to indicate the correct answers, when there are no correct answers

Something to revisit later.

**Comment by jessicasalmon** [comment]
Hey @stianr 

We've addressed the form improvements and Sohil other improvements next week. For now it'd be great if you could test out the form and let us know your thoughts.

### How it looks now
![screen shot 2018-01-26 at 17 33 08](https://user-images.githubusercontent.com/19147734/35453025-9416be58-02c0-11e8-8843-4b84782c92be.png)

### How it looked before
![screen shot 2018-01-26 at 17 34 09](https://user-images.githubusercontent.com/19147734/35453037-9cd43d2c-02c0-11e8-85d9-f2d7e0fdf73a.png)

**Comment by stianr** [comment]
I think that looks great - really good use of space, and much easier to drag questions around now.

**Comment by sohilpandya** [comment]
@stianr the issue related to validation https://github.com/cul-2016/quiz/issues/546#issuecomment-360117574 has also been addressed. We now get slightly more custom error messages.
