### ISSUE TITLE
Going Live

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#550]
I think we're at a stage where we can deploy the app to the main site from the staging area. We're also running out of time, so unless there are any major reasons not to, would it be possible to do that today? We can discard existing user accounts and quizzes as far as I'm concerned, but we'll need to keep or create a single user account that I can access with superuser access.

**Comment by stianr** [comment]
All looking good on the live version. A couple of quick questions for @sohilpandya or @jackcarlisle:

1. We'll need one account with superuser access to download the quiz response csvs. That was lecturer@city.ac.uk, but it doesn't seem to have that access now. From now on it would be best to attach it to the account for stian.reimers@city.ac.uk. The lecturer@city.ac.uk isn't a real email address, so if for any reason the password got lost there's no way of resetting.
2. It looks like accounts and quizzes that were created in Quodl before are still available. Is this permanently so - would be handy for some lecturers, but not sure if it could lead to issues or conflicts. No problem if you have to wipe everything now, but could you let me know either way so I can inform the lecturers.

Excited about using this for real - we have four lecture courses (including mine) ready to go, and the new intake of 200 first years have been primed about using it. Fingers crossed. Thanks again, as ever.

**Comment by sohilpandya** [comment]
Hey Stian,

Glad to hear it’s all looking good. I can’t make that change regarding super user rights but will check with Jack and get that sorted. 

With regards to the quizzes we’ve just left the data as is and not touched it so that it’s intact. Would you like us to wipe it? It will require some extra time for that.

**Comment by jackcarlisle** [comment]
Hi @stianr I could only find the email stian.reimers.1@city.ac.uk 

Is that the one you're talking about?

**Comment by jackcarlisle** [comment]
Hi @stianr that's now done

**Comment by stianr** [comment]
Thanks @sohilpandya - I'm very happy for the existing data to be left, if there's no risk that it'll have any impact on any future use. So if that's the case, I'll tell people they can log in.
@jackcarlisle when I log in to the stian.reimers.1@city.ac.uk account, I still don't see the admin dashboard link. You were completely right that stian.reimers@city.ac.uk was a student rather than lecturer account, so best to apply the superuser access to stian.reimers.1@city.ac.uk.

**Comment by jackcarlisle** [comment]
Hi @stianr that's now been added for stian.reimers.1.ac.uk

**Comment by stianr** [comment]
Brilliant - all working. Thanks @jackcarlisle!
