### ISSUE TITLE
A couple of odd responses

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#560]
In the answer dataset which I can download from the admin dashboard, I found a couple of entries where the item and quiz for a response did not match (I've anonymised email addresses):

lecturer_email@email.com | 1007 | RB | studentemail@email.com | - | 46 | 253 | c | d
-- | -- | -- | -- | -- | -- | -- | -- | --
lecturer_email@email.com | 1007 | RB | studentemail@email.com | - | 46 | 256 | a | a

Questions 253 and 256 are not associated with quiz 46, so I'm not sure how we could have got an entry like that. Very rare, so not a major priority unless it sheds light on anything other issues.

**Comment by stianr** [comment]
To add to this, it's been reported again. Lecturer running "BIOP" quiz_id=64 said "the app indicated a score of 0 with someone who had answered all questions correct." Looking at the data, there were three students whose data was like the above - their responses to questions 306, 307, 308, 309, 310, 311, 315, 316 were associated with module_id="1004" and quiz_id=66,  even though those question IDs were for quiz_id=64 and module_id="BIOP". This means they've got a score of 0 for "BIOP" quiz 64, where they should have got a higher score, and now have a score above the maximum possible in "1004" quiz 66.

**Comment by sohilpandya** [comment]
Hey Stian, we've been looking into the comments you've made above and found the issue that was causing the students to submit questions with the incorrect quiz_id. 

When a student had an existing quiz running and left the browser on the phone, returned to the app at a later stage when another lecturer was running a different quiz, it was picking up on the original quiz_id and not the latest one. 

We'll be pushing up the changes to the live app at the end of the day, nothing to test from your end in this case, but we need to keep an eye out to see if this issue occurs again. 

We'd also like to ask if you want us to update the module quiz_id for the ones you've mentioned in the comment https://github.com/cul-2016/quiz/issues/560#issuecomment-341136434 manually or leave them as is?

**Comment by stianr** [comment]
That's good news @sohilpandya - thanks for fixing it. Please do update the database for those mentioned in my first two comments. I'm assuming that will correct their overall score and leaderboard position, which is most important, but won't change the badges they'd been awarded, which is fine.

**Comment by sohilpandya** [comment]
Hi @stianr, we've updated the quiz_id for both the comments that you've made above. We also managed to find another user in 64 whose quiz_id was referring to 51, we've changed that too. 

The scores for these modules should now be correct. Is it possible for you to test and get back to us. Thanks

**Comment by stianr** [comment]
This issue hasn't arisen since the fix was made, so it looks like it's fixed.
