### ISSUE TITLE
Migration of database to AWS

### ISSUE THREAD

**Issue by iteles** [cul-2016/quiz#568]
In order to remedy the scalability issues presented in #553, the postgres database has been updated on heroku.

As a Quodl product owner, 
I would like to migrate the database to AWS RDS
As this is a cheaper alternative to what we have now.

As per https://github.com/cul-2016/quiz/issues/553#issuecomment-337389189

@stianr Could you please clarify whether you would also like legacy data to be migrated as part of this issue?

**Comment by stianr** [comment]
Hi @iteles. If we're going to migrate before December (which seems sensible if we're confident there won't be a high risk of issues for users), we'll need to migrate the data as well, as students will be part way through a module and won't want to re-register and reset their scores.

**Comment by Danwhy** [comment]
I've completed the migration of the database today, and found that the equivalent database to what we were using on heroku should actually be about half the price on aws. ($50 vs approximately $24.89)

I also implemented the automatic downgrading of the database on the weekend (between midnight Friday and 5am Monday morning), when the app will see the least use, which will reduce the cost even further (to approximately $18 per month). This can be extended or reduced as much as is necessary.

Upgrading to the next tier of the database if necessary would also be very simple, both manually if we wanted to try it out, and automatically at the end of the weekends if we wanted to keep it.

Backups happen automatically daily, and are kept for 7 days, but this can be extended.

The data is stored in the UK and should never leave the EU: https://aws.amazon.com/compliance/eu-data-protection/

**Comment by iteles** [comment]
@Danwhy Thank you for this! To finish off this issue, can we also look to update the documentation and migration processes please? https://github.com/cul-2016/quiz#deployment

**Comment by stianr** [comment]
Fantastic. Thanks @Danwhy!

**Comment by Danwhy** [comment]
Hi @stianr I used my own credit card to sign up for the aws account. I've emailed you the login details for the account, so would you be able to sign in and add your own card so I can remove mine?

Once you log in, just click 'quodl' in the navbar, then 'My Account', then go to 'Payment Methods'. 

Let me know once you've done it and I'll remove my card and my access to the billing information. I've added myself and sohil as admin users, so we'll be able to access everything except billing after that.

**Comment by stianr** [comment]
Hi @Danwhy thanks for using your credit card details - I've now added mine, so safe to delete yours I think.

**Comment by Danwhy** [comment]
Great, thanks @stianr I've done that, so feel free to change the password/name/email of the aws account now if you wish. @sohilpandya and I will still be able to access the database from our accounts if we need to.

**Comment by stianr** [comment]
Closing this, as all seems to be running smoothly post-migration.
