### ISSUE TITLE
Reset Password Page Not Working

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#569]
If I go to the main page at www.quodl.co.uk and click on the 'Forgotten Password' link, nothing happens, I am not redirected, and I am unable to reset my password. Problem replicated in both Chrome and Firefox for PC. This is a new bug - the reset password functionality was working fine a week or two ago. I am in the middle of setting up a new lecturer account, and they will not be able to get access until they can set their own password using that link.

**Comment by stianr** [comment]
Great! Is it possible to deploy this, @sohilpandya, as I have a lecturer who needs to reset their password, and can't log on until they do?

**Comment by sohilpandya** [comment]
I'll do that as soon as its merge. should be done soon.

**Comment by sohilpandya** [comment]
@stianr this should now be working, could you please test this.

**Comment by stianr** [comment]
Thanks @sohilpandya - all seems to be working.
