### ISSUE TITLE
GDPR Compliance with migration to AWS

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#572]
As product owner, I want to ensure that users' data is protected, and that Quodl is GDPR compliant.

When we migrate database provision from Heroku to AWS (#568), we will need to ensure that the data is physically stored within the EU. It looks like AWS offers this capability, but we will need to ensure that we configure AWS setup appropriately.

**Comment by iteles** [comment]
@stianr Definitely possible with AWS when we come to it 👍🏻

**Comment by iteles** [comment]
This has now been completed for AWS.
