### ISSUE TITLE
Transitions between questions Chrome/Android

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#582]
At last I seem to have identified a replicable version of the transitions problem that we saw earlier in the term. It seems to occur specifically on chrome for Android. I've replicated it on my own Galaxy S7 after a student showed it on her J5. If you try completing a live quiz, the transitions between questions are incredibly slow, and the screen is blank for much of the time. It can take 30 seconds for a question to appear, and seems to get worse as the quiz progresses (though that may not be a consistent effect).

**Comment by iteles** [comment]
We have tried to replicate this unsuccessfully on a Nexus 5X but have dug up another older Android phone to try this.

It could also be a function of the number of questions in the quiz (our test quiz only had 3), the number of students taking it at once or the network itself.

**Comment by stianr** [comment]
Just tried again: The problem didn't occur with a short, simple quiz (2 questions, minimal text), but reappeared when running a longer quiz, so hopefully you'll be able to see it on your devices.

To try to replicate the issue, import this quiz into Quodl as lecturer: BJ4s1HZGf and then run as usual, using Chrome on Android as a student to respond. I found that by Q3 transitions were getting unworkably long. 

(Fwiw, I used a Galaxy S7 with Chrome 63.0.3239.111 / Android 7.0, so I don't think it's down to processor speed or similar. But agree,)

**Comment by stianr** [comment]
Okay, to isolate the cause further, I tried two separate quizzes. One had 8 two-option short questions (you can import with this code: Bkig5-TVz); the other had three extremely wordy questions (rkT_9W64G). The first ran fine, the second started stuttering at the first question. It even struggled when I reduced the number of options to 2 (but each option contained a fair amount of text). So it looks like it's the amount of text in a question and its options that is causing the problem. 

Again, no problem running this on the same phone with FireFox.

**Comment by iteles** [comment]
Thanks for that @stianr, excellent detective work 🔎

**Comment by sohilpandya** [comment]
Hey, just an update, we have some transitions which look to be the cause of this, we've removed them on the local version and the lag is not there anymore. 

Still work in progress, will try out other method for animation and report back here.

**Comment by sohilpandya** [comment]
Looks like there seems to be an animation issue on chrome mobile. We've tried to use other Greensock methods and CSS transform both perform really well on iPhone (chrome & safari) and desktop but not on Android running 7.0.1 with chrome mobile(Sony Xperia).

We will stop the spike and move onto other tasks, will research a little further and see if we can solve this, alternatively, we can just remove the animations between questions. That would be the last resort if we are unable to find a solution.

**Comment by stianr** [comment]
Thanks @sohilpandya. If it's possible to easily remove the animations just from Chrome (or better still just from Chrome mobile), but retain it elsewhere, then I'd suggest doing that and moving on to other issues. If it means losing the animations for all browsers, it's probably worth looking at further.

**Comment by stianr** [comment]
This isn't working for me - transitions still very slow with wordy questions. Screen recording to illustrate here:

https://www.dropbox.com/s/noei2xk6vux6cul/20180126_111917.mp4

**Comment by stianr** [comment]
You could see if it replicates using 'Testing Stian - Wordy' on lecturer account or importing S1W2x5dBf

**Comment by sohilpandya** [comment]
Hi @stianr, 

Apologies it looks like the changes aren't reflected on the staging site just yet. Will update you as soon as they are pushed and ready for you to test.

**Comment by stianr** [comment]
Ah right, will hang on for testing these developments...

**Comment by sohilpandya** [comment]
@stianr, this is ready for you to test again. 

I'd recommend that you wait around 10/25 seconds on the holding screen before proceeding with starting the quiz, as you would when running it live to wait for students.

**Comment by stianr** [comment]
@sohilpandya it's still looking the same for me, with slow transitions. Do you want me to share a screen recording?

**Comment by sohilpandya** [comment]
Hmm, that is interesting. I've trialled it on the chrome browser with a Sony Xperia and a Google Nexus 5 phone multiple times and the transitions seem to be very smooth. 

Screen recording won't really help as we won't be able to debug it.

**Comment by stianr** [comment]
I've just tested this again now, and it seems to be working, with smooth transitions. I wonder if it wasn't fully pushed through to the staging site, or was partly cached somewhere when I tried to run it. Anyway I think that's the problem fixed - thanks @sohilpandya!
