### ISSUE TITLE
Giving students information about answers

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#583]
Pulling out and expanding an issue from #485.

As a lecturer, I want to be able to offer students guidance on why a particular answer is correct, by entering explanatory text, or links to other resources. As a student, I want to be able to see why a particular answer is correct, and find out more about the material covered.

To achieve this, I think the following would be needed

- In lecturer edit quiz, for each question, below the four options, include a new full-width field ‘More information for students’, saving input in the same way as for the four options.
- On student quiz ‘review my answers’ section, if the 'more information' string associated with a question is longer than 2 characters, include a section below the question and options that presents that text. Should automatically detect and convert URLs to clickable links.

**Comment by stianr** [comment]
Note that we should talk about whether at this point we could/should also implement #291, allowing up to 7 options for a question rather than the current 4. Functionally it looks similar to this - increasing the input fields and storage for each question in a quiz. But it would be extra work wrt appearance during quiz and review, so probably beyond scope.

**Comment by stianr** [comment]
This seems to be working well. 

I'm guessing that as part of this, the formatting of the student review/revise quiz has changed a bit. This is how it was before:

![image](https://user-images.githubusercontent.com/16817089/35484984-89617246-0450-11e8-9f94-11a3b4cd3372.png)

and this is how it is now: 

![image](https://user-images.githubusercontent.com/16817089/35485034-361e7600-0451-11e8-8752-fe932fe99b44.png)

with much wider spacing between options. If it's possible to revert to the previous version, which I think is neater, that would be great.

**Comment by sohilpandya** [comment]
Hi @stianr,

Can you please let me know where this is taking place? I've just looked at it on an iPhone 7 and it all looks ok for both review and revise. 

<img width="397" alt="screen shot 2018-01-30 at 10 03 25" src="https://user-images.githubusercontent.com/2305591/35560294-eba09270-05a4-11e8-9f8f-a41a52187c86.png">
<img width="411" alt="screen shot 2018-01-30 at 10 03 15" src="https://user-images.githubusercontent.com/2305591/35560295-ebbf747e-05a4-11e8-893d-aa395d103164.png">

**Comment by stianr** [comment]
Seeing this on android Galaxy S7 using Firefox, Chrome and Samsung's own browser.

**Comment by stianr** [comment]
Also on a Win 7 desktop/Chrome

**Comment by stianr** [comment]
The saving and presenting side of this all seems to be working very well. I've pulled out the formatting side out into a separate issue.
