### ISSUE TITLE
Automatic progression through questions

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#585]
As a student taking a quiz, I want to know when I need to make a response, so that I don't run out of time and miss out on getting a point.

One option:
- During quiz question presentation, display a countdown timer bar counting down for 30 seconds. When it reaches zero, auto-advance to the next question (identical to if the lecturer clicked ‘next’)

- Include a ‘pause’ button to stop the countdown timer in case the lecturer wants to give more time

- Make it visually obvious at least on lecturer screen when <5s remain

- Keep the ‘next’ button in case lecturer wants complete control (or question is very easy)

A second option
- When a lecturer presses 'next question', make it visually obvious on the lecturer's screen, and start a 5-second countdown, before moving on to the next question

- Change the background colour for the student's view for the last 5 seconds to warn them that they need to answer

**Comment by stianr** [comment]
Hi @sohilpandya, as we don't have a time estimate for this yet, I thought I'd jump in first and try to simplify it as much as possible (and take into account user feedback).

This is what I've come up with. Put a timer on the bottom left of the screen with three clickable elements: A circle which shows the remaining time, an up arrow and a down arrow. 

![time](https://user-images.githubusercontent.com/16817089/34997188-b0752642-fad3-11e7-8693-ef27b193f0dc.JPG)

- Initially, time is set to 30s.
- Clicking on the circle toggles the timer on and off, when on, it decreases the remaining time every second, and updates value in circle.
- If it reaches 0, automatically advance in the same way as pressing the 'next question' button. 
- Pressing the up arrow increases the remaining time by 5s
- Pressing the down arrow decreases the remaining time by 5s iff time remaining >=15s

Hopefully this can all be controlled within page, so won't need any interaction with the server.

**Comment by sohilpandya** [comment]
Hi Stian, apologies, looks like I missed adding the estimate on this issue. 

This is the solution which I was thinking about:
- When Lecturer selects next, create a timer on every users phone  (5 seconds)
- Once the timer has completed then move to the next question.
- require some UI input from Harry as to how visual we get on the student screen. 

- 2.5 Days

The option you have described is also another possibility and unlike the option above it keeps the interactions to just the lecture side of things. ~T 2d for the above options. 

Hope this helps.

**Comment by stianr** [comment]
Thanks @sohilpandya. I like your suggestion.

I'll get some feedback from lecturers about what they think would be most useful.

**Comment by jessicasalmon** [comment]
Hey @stianr 

Here's some notes on how the timer works:

* has a default duration of 30 seconds
* the timer can be started and stopped by clicking on it
* by default it is turned off but once turned on for one question, the timer on subsequent questions will start automatically
* allows the user to customise the duration in 5s increments up or down
* if the duration has been customised, the next question will also be set to that custom duration
* if there is less than 15s remaining, the time cannot be decreased
* when there are less than 5s remaining, the timer changes colour to warn students
* when the timer reaches zero, the quiz automatically progresses to next question

Depending on how we're doing for time later on we may be able to adjust the styling. 

Also, do you envisage questions being longer than 60 seconds? If not we'll cap it.

**Comment by stianr** [comment]
This is great - thanks @jessicasalmon! Does exactly what lecturers would like it to do. I like the fact that the default time for subsequent questions is set to whatever the time on the current question is - so lecturers could have a 15s quick-fire version of the quiz without having to adjust the timer on each question. I hadn't thought of doing it like that. The red colour change is great too!

Any further edits would be low priority, and the icing on the cake, but if time allows, when the timer reaches zero and it progresses to the next page, the clock resets to 30s before the next page has loaded and the red colour isn't reset for a second or so. This means that what the users sometimes see is Clock reaches zero -> clock resets to 30s (while still red) -> new page loads and clock changes position -> clock changes from red to blue and starts counting down. A cleaner flow would be that the clock reaches zero, and stays on zero until the next page loads, then in its new position, concurrent with presenting all the other elements on the page it's reset to 30s, blue. and starts counting down again. (Alternatively, you might get the same effect for less effort if the clock just disappears once it's run down and reappears when the new page is loaded. Or possibly even less effort, just make the clock invisible for 2s once it's counted down, and that should then mask the series of changes it goes through, for pretty much all typical load times.)

The only other thing might be if as @sohilpandya mentioned you do any further styling on the timer, make the circle around the second counter a little smaller, and for the final 5 second make the change to red even more salient - e.g., by having the circle filled red with digits in white or something similar.

But it's a great addition to the app - unless there's practical reason for it, I'd leave it uncapped - I doubt many lecturers would want to allow more than 60s, but no reason not to let them if for any reason they want to. I wouldn't worry about issues around fitting 3 digits in the circle - given so few people will use that, I don't have a problem with that looking a bit messier...,

**Comment by iteles** [comment]
@stianr It would probably be advantageous to split out these low priority edits into a separate issue so that we can note the original issue is closed and have the enhancements separately.

**Comment by stianr** [comment]
Good plan. Will do. Can probably do that elsewhere too.
