### ISSUE TITLE
As a lecturer I can add a module

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#6]
- Title  

- **unique** 4 letter code  

- Trophy Defaults  
    1) participation: n quizzes completed (defaults to 3)  
    2) finish first quiz - get a trophy **this is a default that the lecturer cannot change**  
    3) overall 70% across all quizzes in the module - gets a trophy **only applied once the lecturer has chosen a final quiz**  This is the average of the percentages  
    4) getting 100% in any one quiz - gets a trophy  

- Medal Defaults  
     1) 40-50% - Bronze  
     2) 51-70% - silver  
     3) 71% - gold  
     4) 0-39% white  

**Trophies**: All of these can be adjusted with the exception of no. 2

**Comment by sohilpandya** [comment]
Should a lecturer be able to edit a module? 

For e.g. adjust trophy thresholds after a module has been created (or multiple quizzes have been run)

**Comment by sohilpandya** [comment]
Trophy Default - 3) calculation should be the average of percentages for each quiz ( e.g avg. 60%, 80% => 70% regardless of the no. of questions )

**Comment by minaorangina** [comment]
**Estimated time: 4 days**

**Comment by stianr** [comment]
Lecturer shouldn't be able to adjust thresholds once the first quiz has been run (or for simplicity, once the set of quizzes has been set up). If they were allowed to adjust later, it would get complicated notifying people who gained or lost a trophy because of the change.

**Comment by minaorangina** [comment]
@stianr Thanks for clearing that up

**Comment by stianr** [comment]
Noticed that the participation trophy would also have to wait until the final quiz is run, because the system doesn't know how many quizzes there are until the final one is specified, so can't work out a proportion. Maybe we should have it as a fixed number of quiz submissions (default, say, 3), rather than a proportion of all.

**Comment by minaorangina** [comment]
@stianr Ok that makes sense, we will go with your suggestion

**Comment by minaorangina** [comment]
@stianr could you clarify something for us please?  Currently one of the trophies is awarded if you get 100% on any quiz.  Should this be editable?  For instance, a lecturer could decide to award the trophy if a student gets 90% on any quiz.

**Comment by stianr** [comment]
If it’s easy enough to have it as editable, then yes, that’d make sense – in case some lectuerers want to run longer quizzes where students don’t stand much of a chance of getting 100%.

**Comment by sohilpandya** [comment]
TODO:
- [ ] Validation checks
- [ ] Styling
