### ISSUE TITLE
Calculate Percentile for Student (custom feedback)

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#60]
#121 
To Calculate Percentile. 

-> Take the mean percentage of all the quizzes for all the students that have completed a given module.

* q1 = 50%, q2 = 100%, q3 = 60% then average = 70%

-> Sort the students in an descending order of percentage
* [ 100,70,66,55,33,25,12,11,6,2 ]

-> calculate the percentile for the following ranges 
* 0-10% 
* 11-25%
* 26-50%  
* 51-90%

  returns [ 1, 2, 4, 7] represents the boundaries

We then need to calculate where the given students belong on the percentile. 

What happens when the list of scores have duplicates? 
i.e. [ 1, 3,3, 60, 70, 90, 100, 100 ]

**Comment by minaorangina** [comment]
There some maths libraries that will help calculate percentiles.

* [numbers.js](http://numbers.github.io) has a [__numbers.statistic.quantile__ method](http://numbers.github.io/statistic.html#quantile) (percentile is a type of quantile, [see here](http://stats.stackexchange.com/questions/156778/percentile-vs-quantile-vs-quartile))

* [Simple Statistics](http://simplestatistics.org/) also has a [quantile method](http://simplestatistics.org/docs/#quantile).  Think this one can take an array of quantiles too...?

**Comment by minaorangina** [comment]
Relates to user story #121

**Comment by minaorangina** [comment]
Will calculate 11%, 14% and 51%

**Comment by minaorangina** [comment]
Quiz 3, 10 questions.  Answers:

1. a 
2. b 
3. c 
4. d 
5. d 
6. c 
7. b 
8. a 
9. d 
10. b

**Comment by minaorangina** [comment]
|User|score|percentage|
|---|---|---|
|Homer| 1 | 10 |
|Marge| 1 | 10 |
|Lisa| 1 | 10 |
|Bart| 1 | 10 |
|Maggie| 2 | 20 |
|Ned| 2 | 20 |
|Apu| 2 | 20 |
|Smithers| 2 | 20 |
|Mr Burns| 3 | 30 |
|Rev Lovejoy| 3 | 30 |
|Milhouse| 3 | 30 |
|Nelson| 3 | 30 |
|Patty| 4 | 40 |
|Selma| 4 | 40 |
|Comic Book Guy| 4 | 40 |
|Krusty| 4 | 40 |
|Sideshow Bob| 5 | 50 |
|Sideshow Mel| 5 | 50 |
|Dr Nick| 5 | 50 |
|Principal Skinner| 5 | 50 |
