### ISSUE TITLE
Request Failed with status code 400

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#605]
Attempting to add quizzes seems to give an error now on the 'New Quiz' page. The quiz is not saved.

**Comment by sohilpandya** [comment]
Thanks for raising this @stianr, this is likely the cause of the added validation that @eliascodes and I put in yesterday. 

I've found the issue and will be fixing it.

Thanks

**Comment by stianr** [comment]
I encountered this once since this update but haven't been able to replicate it. Will open and update if I see it again.
