### ISSUE TITLE
Persist user data - localstorage for the user state. 

### ISSUE THREAD

**Issue by minaorangina** [cul-2016/quiz#61]
Solution 1 - fetch user data on enter

Solution 2 - fetch from local storage

https://github.com/tayiorbeii/egghead.io_idiomatic_redux_course_notes/blob/master/03-Persisting_the_State_to_the_Local_Storage.md

**Comment by minaorangina** [comment]
Should use `lodash.throttle` to prevent writing to local storage too often

**Comment by sohilpandya** [comment]
**Places where the app state breaks app on refresh**

- `module_id/lecturer/live`
    - when lecturer selects start quiz, it required module_id and it is undefined in the state, alternative would be to get the module_id from the params in URL
