### ISSUE TITLE
Formatting of review/revise quiz

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#613]
As a student I want to see quizzes I've previously taken presented neatly and concisely. Pulling this issue out of #583.

The ideal formatting was something like this:

![image](https://user-images.githubusercontent.com/16817089/35614610-995e141a-0667-11e8-8b9a-e164ce55b244.png)

Currently, the formatting is like this:

![image](https://user-images.githubusercontent.com/16817089/35614662-c1b9451a-0667-11e8-9fb4-59b77d572a25.png)

And appears this way on my testing with Android Firefox/Chrome/Samsung browser, iPhone 5 and Desktop/Chrome but @sohilpandya says it displays fine on iPhone 7. It would be good to get it to look like the formatting in the first image across all devices, without the big gaps between options.

**Comment by stianr** [comment]
This now looks fixed. Looks great. Happy for this to be closed, but as it doesn't have please-test label, I'll hold off in case there's anything else you want to do at your end.

**Comment by sohilpandya** [comment]
Happy for you to close @stianr
