### ISSUE TITLE
Additional Super Admin Functionality

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#620]
All payments will be done manually, so we need to have an area where the super admin can add a client. 

- Super Admin will navigate to the super admin area
    - [x] Add a new button called ‘add a client’ 
    - [x] Provide a form with the following fields:
        - Name
        - Email
        - Account type: Group (in which case add group_admin to true) or Individual which will not do anything here.  
        - Institution
        - Department  
        - Paid: Yes/No 
    - [x] Save the client 
  
- When the client is saved, we will need to do two things:
    - [x] For a Group admin, Send an email with the code to the user above asking them to sign up using the same email and code we have for them, this is how we will identify if they are a group admin. 
    - [x] For an individual, Send an email with no code but confirming payment and asking them to sign up.  (when they sign up we check the account type and paid for letting them in) 
    - [x] Create a new row in the account_management table, with the client, paid(bool) and unique code, linking to the given user. 
    - [x] If the same user is inputted more than once (based on email address), we'll update the existing record, instead of creating a duplicate. 

- [x] We also need to allow the super admin to edit clients,
    - This will happen from super admin home screen where they can already see a list of lecturers
    - When they select edit, they will be taken to the details section
    -  so that they can switch the paid to No if the user stops making payments. And edit any other details if necessary. 
    - This will then affect the rest of the users who are attached to the given group. 

**Please let me know if we have missed any additional fields out.** 
Idea is to use the paid and code fields to check if a given user should have access if they do then we let them continue, otherwise we log them out. 

@jessicasalmon @iteles please have a look and let me know if the above estimates make sense and are ok 👍 or if I've missed something out. :)

**Comment by jessicasalmon** [comment]
TODOS

- [ ] add 'add a client' button to super admin screen
- [ ] create the form 
- [ ] then handle save (both scenarios)
- [ ] then handle edit

**Comment by jessicasalmon** [comment]
TODOS
- [ ] clear state manageClient state when 'add a client' button is pressed from admin dashboard
- [ ] add tests for edit client functionality 
- [ ] ensure super admin cannot change user type from individual lecturer to group admin (and vice versa), to uphold the integrity of the application
 - [ ] prevent email being sent when user is being edited

**Comment by sohilpandya** [comment]
@stianr Please test this issue: 
- use the normal lecturer@city.ac.uk for testing this feature
- add an individual client -> check email receive
- add a group admin -> check the email they receive
- edit the client

**Comment by stianr** [comment]
Adding a client group admin while logged in as superuser generates an email.
- Would it be possible to have the link direct to the lecturer sign-up #/register-lecturer rather than the Quodl root directory? Just makes it a bit smoother. 

Signing up as group admin didn't work 
- I went to the register lecturer page on the staging version, entered the email address and the code from the email (HJO34Se5f), and it said the code was invalid. I'd copied and pasted from the email, so it wasn't a typo. So I'm stuck there, not able to log in as group admin.

**Comment by jessicasalmon** [comment]
Hey @stianr, we've made the following changes, please test:

* email links direct to the lecturer sign-up #/register-lecturer
* signing up as group admin now works

**Comment by stianr** [comment]
Email links: Great! Thanks.
Signing up now works, but when I log in as a new group admin, I don't have a link to my dashboard, so I can't access the group admin functionality (it looks like the whole top menu bar is a logout link).

**Comment by jessicasalmon** [comment]
Hey @stianr - thanks for finding that bug! We've resolved it, please look at it in staging.

**Comment by jessicasalmon** [comment]
Hey @stianr, hope you're well. Could you please test this and close if all is okay. Thanks

**Comment by stianr** [comment]
Again, much belatedly, thanks - all working.
