### ISSUE TITLE
General Authentication Flow Changes

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#624]
Generally, we need to change the flow of authentication for lecturers, we need to check if they have valid access, if they do then continue, otherwise log the user out. This will need to be done as well 
I guess this is where we also need to check if the user has paid the monthly fee, if the group admin has paid then give access, otherwise log the user out and provide a message saying please pay.

We will be tackling this throughout the sprint.

**Comment by jessicasalmon** [comment]
This issue is complete, we've tackled it as we've worked through the sprint.
