### ISSUE TITLE
Existing Lecturers

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#625]
Hi @stianr, Whilst upgrading the database structure we will need to provide some additional detail for the existing lecturers.

Will existing lecturers be treated as paid individual customers or as people who are trial users who now need to pay to upgrade to paid individual account type

**Comment by sohilpandya** [comment]
Currently, we are allowing existing lecturers to log in and use the app as normal. You will have to create a client account for this user (type: individual lecturer) and manage payment from there in order to allow or stop the user from accessing the app in the future.

**Comment by stianr** [comment]
Re the original question, I'd say treating them as paid individual customers would make most sense. That way they'd presumably carry on as currently unless I changed their status to not paid.
Re the update, perhaps we can clarify when we talk next, just so I know what exactly needs to be done.
Not a big issue here, key thing is that current users don't suddenly lose access without manual intervention from me...

**Comment by jessicasalmon** [comment]
We thought that you'd want to continue to allow existing users in the app, so our current flow lets all existing lecturers in. Only new lecturers who sign up will be affected by the new changes. 

If you'd like to stop access for a given lecturer, you would have to create a new client account via the super admin dashboard, and set paid to false.

**Comment by stianr** [comment]
Now I understand better how it works, this is fine as is, so I'll close it
