### ISSUE TITLE
Wording tweaks

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#640]
For the expired individual lecturer subscription please could we change the text from 

Sorry, you haven't made your last payment. Please contact Quodl

to

Your subscription has expired. Please email hello@quodl.co.uk to renew.

**Comment by stianr** [comment]
Your institution has not made the latest payment. Please contact your adminstrator

to

Your institution's subscription has expired. To continue using Quodl, please contact your administrator, or email hello@quodl.co.uk

**Comment by jessicasalmon** [comment]
Hey @stianr, we've updated the text in these emails: please test

**Comment by stianr** [comment]
This is all excellent. Thanks @jessicasalmon.
