### ISSUE TITLE
Remove nickname field from lecturer signup

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#643]
At the moment, the lecturer sign-up /#/register-lecturer has a field for nickname. This is not used for lecturers and may be confusing. Can we hide or remove it?

At the same time could we change the text for the field below to fit on one line, from:

Code (if registering under an institutional account)
to
Code (if your institution has given you one)

**Comment by sohilpandya** [comment]
Hi @stianr, Both of the points above have been tackled. Please test it in staging.

**Comment by stianr** [comment]
Brilliant - looks great. Thanks @sohilpandya.
