### ISSUE TITLE
Basic Group Admin Reporting: Usage

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#644]
As a group admin I want to see how much use Quodl is getting from my lecturers.

In the group admin page, at the moment we have a table that has columns for the email address of the lecturer and a toggle for their activity status. Could we add four more columns, pulling the relevant data from the relevant database:

1. Number of Modules (total number of modules associated with each lecturer account) [Better: list of module codes associated with that account, but not if it takes longer]
2. Number of Students (total number of students enrolled across all modules for that lecturer - can either be the total number of unique students who are enrolled on at least one of the modules, or the sum of the number of students enrolled on each module - which would count students enrolled on multiple modules more than once)
3. Number of quizzes (total number of quizzes either set up or run - preferably run if it's just as easy)
4. Number of responses (total number of quiz answers submitted across all quizzes associated with that lecturer - so if the lecturer ran two quizzes with 5 questions each and 100 students, that would be 1,000 responses)

If time is an issue, probably 2 and 3 are the priorities.

**Comment by stianr** [comment]
Just testing now. On Chrome there are scrollbars that it would be good to remove:

![image](https://user-images.githubusercontent.com/16817089/40361443-442403a4-5dc1-11e8-91d2-d3fb22082dff.png)

**Comment by stianr** [comment]
This is looking good, and I can see how useful it may be to programme directors.

**Comment by stianr** [comment]
Number of responses seems to be double counting - currently showing 24 where there have been 12.

**Comment by stianr** [comment]
Also, download of student responses also includes the lecturer (first row):

![image](https://user-images.githubusercontent.com/16817089/40362520-a1b730b0-5dc4-11e8-9d39-fa8b609c6220.png)

**Comment by Danwhy** [comment]
@stianr These issues should have been addressed now, would you mind testing again?

**Comment by stianr** [comment]
@Danwhy None of these seem to be fixed on the staging version - does it need to be updated?

**Comment by Danwhy** [comment]
@stianr It looks like the automatic deploy failed, I've manually pushed it and it should have updated now

**Comment by stianr** [comment]
This all seems to be fixed now - numbers seem right, and I don't see scrollbars any more. Thanks!
