### ISSUE TITLE
Basic Group Admin Reporting: Analytics

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#645]
As group admin I want to be able to export data from my lecturers so that I can run my own analytics on it.

- Add a single button to download a csv, as with the download-all-data we have in the current superuser admin dashboard
- Check which modules are associated with lecturers in the group
- Check which students are associated with at least one module for that set
- Create a csv file with a row for each student from above, and two columns for each module from above: Quizzes taken; Total score, and populate accordingly (with ‘-‘ for any modules that a student isn’t subscribed to)

**Comment by stianr** [comment]
(If also doing #644, could be easier to combine these and have a button per lecturer row to download the relevant data by lecturer. That would also work.)

**Comment by stianr** [comment]
This looks good - I'm assuming user ID will be email address. Is it also possible to have a column with nickname? Just checking with Yinka re any other comments.

**Comment by Danwhy** [comment]
:+1: Having email address and nickname is fine

**Comment by stianr** [comment]
All working - thanks!
