### ISSUE TITLE
Mobile Formatting

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#657]
In the latest deployment, the formatting of pages to fit mobile screens seems to have gone awry. Found issues using Chrome, Firefox and Samsung's own browser, all with Android. Page either extends beyond the screen so needs scrolling, or is smaller than the screen. See below:

![screenshot_20180510-133731_firefox](https://user-images.githubusercontent.com/16817089/39872050-a70ccbb6-545e-11e8-930c-17a48625f710.jpg)
![screenshot_20180510-133715_firefox](https://user-images.githubusercontent.com/16817089/39872051-a721af7c-545e-11e8-8bcb-a8a4c198acab.jpg)

**Comment by iteles** [comment]
@stianr Is this only in production and not in staging?

**Comment by stianr** [comment]
Hi @iteles, I see it in both the current deployed version at https://app.quodl.co.uk, and on the staging version, which I think is the same, given it was only recently deployed, though I may be wrong there...

**Comment by iteles** [comment]
@stianr We'll take a look at this with some of the allocated time we have in the PO at the moment 👍

**Comment by stianr** [comment]
@Danwhy This looks like it's fixed - thanks! Is it safe to close now?

**Comment by iteles** [comment]
@stianr Definitely 👍

**Comment by stianr** [comment]
This all looks fixed - thanks!
