### ISSUE TITLE
Trial accounts

### ISSUE THREAD

**Issue by Danwhy** [cul-2016/quiz#695]
Hi @stianr,

I've removed the expiry date for all lecturers that were signed up to the app before May 8th, which is when the trial code was added.

There are 8 other lecturer accounts that were created later, and all have an expiry date (the earliest is mid September). Would you like me to remove the expiry from those too, or leave them as trial accounts?

**Comment by iteles** [comment]
@Danwhy I believe this now answered by the creation of #696 😊 

Closing in favour of that issue.
