### ISSUE TITLE
As a lecturer I can add a quiz for a given module

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#7]
- Title
- 1 Question by default
- lecturer can add a new question by selecting a button
- lecturer can save the quiz 
- possible answers will default to 4 but can be reduced to three or two
- lecturer must select a possible answer before moving onto the next question.
- lecturer can mark the quiz as the final one in the module. ( this will not appear if a previous quiz has been selected as the final quiz )

**Comment by minaorangina** [comment]
**3 days**
