### ISSUE TITLE
Fetch Questions and Responses for the review section from the database

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#85]
Trying to create a db call that will fetch all the questions alongside all the responses for each of the questions. 

To get a table as such:
a_response | b_response | c_response | d_response | 
2                     | 3                 | 0                   | 6

```
select 
count(case when response = 'A' then 1 end) as a_response, 
count(case when response = 'B' then 1 end) as b_response, 
count(case when response = 'C' then 1 end) as c_response, 
count(case when response = 'D' then 1 end) as d_response  
from responses 
where quiz_id=1 and question_id=1
```

_**~update~**_ **IGNORE look at update 2 below**

**IGNORE**Here is an updated query, close but not there as it is duplicating and I can't seem to figure out why. @minaorangina can you please have a play with it and see if you can figure out how to stop the duplication?**IGNORE**

Result of the query  

**screenshot 1**
![screen shot 2016-08-12 at 12 11 07](https://cloud.githubusercontent.com/assets/2305591/17620716/21cbe6d0-6086-11e6-813f-95b16f747be2.png)

``` postgres
select distinct questions.quiz_id, questions.question_id, questions.question, questions.a, questions.b, questions.c, questions.d, questions.correct_answer,
( select count(case when responses.response = 'A' then 1 end) as a_response
    from responses
    where responses.question_id = questions.question_id
    group by responses.question_id ),
( select count(case when responses.response = 'B' then 1 end) as b_response
    from responses
    where responses.question_id = questions.question_id
    group by questions.question_id ),
( select count(case when responses.response = 'C' then 1 end) as c_response
    from responses
    where responses.question_id = questions.question_id
    group by questions.question_id ),
( select count(case when responses.response = 'D' then 1 end) as d_response
    from responses
    where responses.question_id = questions.question_id
    group by questions.question_id )
from questions
left join responses
    on questions.question_id = responses.question_id
    where questions.quiz_id = 1
    order by questions.question_id;
```

**update 2**

Made it work here is the result and updated the script above to the correct one. just a minor change to make it work. 

Initially I did not add the DISTINCT call hence it will returning multiple records as seen in screenshot 1, but once the DISTINCT call was added in the query it returned the correct number of results for quiz 1. 

**screenshot 2**
![screen shot 2016-08-12 at 12 18 34](https://cloud.githubusercontent.com/assets/2305591/17620859/3b7f1d76-6087-11e6-93ae-bd04ec09c9bd.png)

**Comment by minaorangina** [comment]
@sohilpandya specify what you changed, and why it was wrong, so we have a record of it
