### ISSUE TITLE
Authenticate Student and Lecturer as seperate hooks. 

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#88]
There are some roots that are accessible only by students or lecturers, so if a student decides to go to a lecturer view, we should kick them back out to the homepage. 

for e.g. lecturer/live, lecturer/review etc. should not be accesible by students, so creating an authenticate function specifically for lecturers and students will come in handy as an onEnter Hook

**Comment by minaorangina** [comment]
This problem was solved with issue #141
