### ISSUE TITLE
Manually close a quiz

### ISSUE THREAD

**Issue by minaorangina** [cul-2016/quiz#99]
#9 
If a lecturer needs to close a quiz off without running it, this should be possible.

Also, any active `JOIN THE LIVE QUIZ` buttons should disappear

**Comment by minaorangina** [comment]
* async action to remove all responses for that quiz
* emit end of quiz socket event
* redirect students away from live quiz view

**Comment by sohilpandya** [comment]
Abort Quiz button
 - [ ] when the lecturer aborts a quiz all realted db items should be flushed. (responses & keep is_presented to false)
- [ ] Redirect lecturer to module details
- [ ] Redirect student to module details
- [ ] Message to say the quiz has been aborted
